/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TargetingExpressionList } from './targeting-expression-list';
/**
 * 
 * @export
 * @interface AdGroupThemeBasedBidRecommendationRequest
 */
export interface AdGroupThemeBasedBidRecommendationRequest {
    /**
     * 
     * @type {TargetingExpressionList}
     * @memberof AdGroupThemeBasedBidRecommendationRequest
     */
    targetingExpressions: TargetingExpressionList;
    /**
     * The campaign identifier.
     * @type {string}
     * @memberof AdGroupThemeBasedBidRecommendationRequest
     */
    campaignId: string;
    /**
     * The bid recommendation type.
     * @type {string}
     * @memberof AdGroupThemeBasedBidRecommendationRequest
     */
    recommendationType: AdGroupThemeBasedBidRecommendationRequestRecommendationTypeEnum;
    /**
     * The ad group identifier.
     * @type {string}
     * @memberof AdGroupThemeBasedBidRecommendationRequest
     */
    adGroupId: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AdGroupThemeBasedBidRecommendationRequestRecommendationTypeEnum {
    BIDSFOREXISTINGADGROUP = 'BIDS_FOR_EXISTING_AD_GROUP'
}

