/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AgeRange
 */
export interface AgeRange {
    /**
     * Name of Age Range. This field is OPTIONAL if the Age Range object is being used as an input.
     * @type {string}
     * @memberof AgeRange
     */
    name?: string;
    /**
     * Id of Age Range. This field is REQUIRED if the Age Range object is being used as an input. Use the GetRefinementsForCategory to retrieve Age Range Node IDs.
     * @type {string}
     * @memberof AgeRange
     */
    id?: string;
}
