/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeywordTarget } from './keyword-target';
import { KeywordTargetRankRecommendationRequest } from './keyword-target-rank-recommendation-request';
/**
 * This request type is used to retrieve recommended keyword targets for ASINs. Set the recommendationType to KEYWORD_FOR_ASINS to use this request type.
 * @export
 * @interface AsinsKeywordTargetRankRecommendationRequest
 */
export interface AsinsKeywordTargetRankRecommendationRequest extends KeywordTargetRankRecommendationRequest {
    /**
     * An array list of Asins
     * @type {Array<string>}
     * @memberof AsinsKeywordTargetRankRecommendationRequest
     */
    asins: Array<string>;
    /**
     * The recommendationType to retrieve recommended keyword targets for a list of ASINs.
     * @type {string}
     * @memberof AsinsKeywordTargetRankRecommendationRequest
     */
    recommendationType: AsinsKeywordTargetRankRecommendationRequestRecommendationTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AsinsKeywordTargetRankRecommendationRequestRecommendationTypeEnum {
    KEYWORDSFORASINS = 'KEYWORDS_FOR_ASINS'
}

