/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BiddingStrategy } from './bidding-strategy';
import { PlacementAdjustment } from './placement-adjustment';
/**
 * Bidding control configuration for the campaign.
 * @export
 * @interface AsinsThemeBasedBidRecommendationRequestBidding
 */
export interface AsinsThemeBasedBidRecommendationRequestBidding {
    /**
     * Placement adjustment configuration for the campaign.
     * @type {Array<PlacementAdjustment>}
     * @memberof AsinsThemeBasedBidRecommendationRequestBidding
     */
    adjustments?: Array<PlacementAdjustment>;
    /**
     * 
     * @type {BiddingStrategy}
     * @memberof AsinsThemeBasedBidRecommendationRequestBidding
     */
    strategy: BiddingStrategy;
}
