/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Bid value of the bid recommendations
 * @export
 * @interface BidValue
 */
export interface BidValue {
    /**
     * The suggested bid.
     * @type {number}
     * @memberof BidValue
     */
    suggestedBid: number;
}
