/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrandLoP } from './brand-lo-p';
/**
 * List of Brands.
 * @export
 * @interface BrandsLoP
 */
export interface BrandsLoP extends Array<BrandLoP> {
}
