/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BudgetUsagePortfolio } from './budget-usage-portfolio';
import { BudgetUsagePortfolioBatchError } from './budget-usage-portfolio-batch-error';
/**
 * 
 * @export
 * @interface BudgetUsagePortfolioResponse
 */
export interface BudgetUsagePortfolioResponse {
    /**
     * List of budget usage percentages that were successfully pulled
     * @type {Array<BudgetUsagePortfolio>}
     * @memberof BudgetUsagePortfolioResponse
     */
    success?: Array<BudgetUsagePortfolio>;
    /**
     * List of budget usage percentages that failed to pull
     * @type {Array<BudgetUsagePortfolioBatchError>}
     * @memberof BudgetUsagePortfolioResponse
     */
    error?: Array<BudgetUsagePortfolioBatchError>;
}
