/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BudgetRecommendationRequest
 */
export interface BudgetRecommendationRequest {
    /**
     * List of campaigns.
     * @type {Array<string>}
     * @memberof BudgetRecommendationRequest
     */
    campaignIds: Array<string>;
}
