/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BudgetUsageCampaign } from './budget-usage-campaign';
import { BudgetUsageCampaignBatchError } from './budget-usage-campaign-batch-error';
/**
 * 
 * @export
 * @interface BudgetUsageCampaignResponse
 */
export interface BudgetUsageCampaignResponse {
    /**
     * List of budget usage percentages that were successfully pulled
     * @type {Array<BudgetUsageCampaign>}
     * @memberof BudgetUsageCampaignResponse
     */
    success?: Array<BudgetUsageCampaign>;
    /**
     * List of budget usage percentages that failed to pull
     * @type {Array<BudgetUsageCampaignBatchError>}
     * @memberof BudgetUsageCampaignResponse
     */
    error?: Array<BudgetUsageCampaignBatchError>;
}
