/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The Error Response Object.
 * @export
 * @interface CampaignOptimizationRuleError
 */
export interface CampaignOptimizationRuleError {
    /**
     * An enumerated error code for machine use.
     * @type {string}
     * @memberof CampaignOptimizationRuleError
     */
    code?: string;
    /**
     * A human-readable description of the response.
     * @type {string}
     * @memberof CampaignOptimizationRuleError
     */
    details?: string;
}
