/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CampaignOptimizationId } from './campaign-optimization-id';
/**
 * 
 * @export
 * @interface DeleteSPCampaignOptimizationRuleResponse
 */
export interface DeleteSPCampaignOptimizationRuleResponse {
    /**
     * 
     * @type {CampaignOptimizationId}
     * @memberof DeleteSPCampaignOptimizationRuleResponse
     */
    campaignOptimizationId?: CampaignOptimizationId;
    /**
     * An enumerated success or error code for machine use.
     * @type {string}
     * @memberof DeleteSPCampaignOptimizationRuleResponse
     */
    code?: string;
    /**
     * A human-readable description of the error, if unsuccessful
     * @type {string}
     * @memberof DeleteSPCampaignOptimizationRuleResponse
     */
    details?: string;
}
