/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Request object to retrieve Category Recommendations based on the input ASINs.
 * @export
 * @interface GetCategoryRecommendationsForAsinsRequest
 */
export interface GetCategoryRecommendationsForAsinsRequest {
    /**
     * List of input ASINs. This API does not check if the ASINs are valid ASINs.
     * @type {Array<string>}
     * @memberof GetCategoryRecommendationsForAsinsRequest
     */
    asins?: Array<string>;
    /**
     * Enable this if you would like to retrieve categories which are ancestor nodes of the original recommended categories. This may increase the number of categories returned, but decrease the relevancy of those categories.
     * @type {boolean}
     * @memberof GetCategoryRecommendationsForAsinsRequest
     */
    includeAncestor?: boolean;
}
