/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CampaignOptimizationRule } from './campaign-optimization-rule';
/**
 * 
 * @export
 * @interface GetSPCampaignOptimizationRuleResponse
 */
export interface GetSPCampaignOptimizationRuleResponse {
    /**
     * 
     * @type {CampaignOptimizationRule}
     * @memberof GetSPCampaignOptimizationRuleResponse
     */
    campaignOptimizationRule?: CampaignOptimizationRule;
}
