/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Impressions benchmark.
 * @export
 * @interface Impressions
 */
export interface Impressions {
    /**
     * lower bound.
     * @type {number}
     * @memberof Impressions
     */
    lower?: number;
    /**
     * upper bound.
     * @type {number}
     * @memberof Impressions
     */
    upper?: number;
}
