/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Contains suggested recommendation for the keyword targeting.
 * @export
 * @interface KeywordTargetingRecommendation
 */
export interface KeywordTargetingRecommendation {
    /**
     * The identifier of the keyword targeting.
     * @type {string}
     * @memberof KeywordTargetingRecommendation
     */
    keywordId?: string;
    /**
     * The suggested bid value associated with this keyword targeting clause.
     * @type {number}
     * @memberof KeywordTargetingRecommendation
     */
    suggestedBid?: number;
    /**
     * Keyword match type. | Value | Description | | --- | --- | | `BROAD` | Use BROAD to broadly match your keyword targeting ads with search queries.| | `EXACT` | Use EXACT to exactly match your keyword targeting ads with search queries.| | `PHRASE` | Use PHRASE to match your keyword targeting ads with search phrases.|
     * @type {string}
     * @memberof KeywordTargetingRecommendation
     */
    matchType?: KeywordTargetingRecommendationMatchTypeEnum;
    /**
     * Type of action for the keyword targeting.
     * @type {string}
     * @memberof KeywordTargetingRecommendation
     */
    action?: KeywordTargetingRecommendationActionEnum;
    /**
     * The ad group identifier.
     * @type {string}
     * @memberof KeywordTargetingRecommendation
     */
    adGroupId?: string;
    /**
     * The keyword text.
     * @type {string}
     * @memberof KeywordTargetingRecommendation
     */
    keywordText?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum KeywordTargetingRecommendationMatchTypeEnum {
    EXACT = 'EXACT',
    PHRASE = 'PHRASE',
    BROAD = 'BROAD'
}
/**
    * @export
    * @enum {string}
    */
export enum KeywordTargetingRecommendationActionEnum {
    ADD = 'ADD',
    REMOVE = 'REMOVE',
    INCREASE = 'INCREASE',
    DECREASE = 'DECREASE',
    UPDATE = 'UPDATE'
}

