/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeywordTargetResponse } from './keyword-target-response';
/**
 * 
 * @export
 * @interface KeywordRankedTargetsResponse
 */
export interface KeywordRankedTargetsResponse {
    /**
     * A list of ranked keyword targets
     * @type {Array<KeywordTargetResponse>}
     * @memberof KeywordRankedTargetsResponse
     */
    targets?: Array<KeywordTargetResponse>;
}
