/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The advertising performance metric.
 * @export
 * @enum {string}
 */
export enum PerformanceMetric {
    ACOS = 'ACOS',
    CTR = 'CTR',
    CVR = 'CVR',
    ROAS = 'ROAS'
}

