/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A range of prices. We use this to retrieve the number of targetable ASINs that falls within this price range.
 * @export
 * @interface PriceRange
 */
export interface PriceRange {
    /**
     * 
     * @type {number}
     * @memberof PriceRange
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof PriceRange
     */
    max?: number;
}
