/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeywordTarget } from './keyword-target';
import { KeywordTargetRankRecommendationRequest } from './keyword-target-rank-recommendation-request';
/**
 * This request type is used to retrieve recommended keyword targets for an existing ad group. Set the recommendationType to KEYWORD_FOR_ADGROUP to use this request type.
 * @export
 * @interface RankedKeywordTargetsForAdGroupRequest
 */
export interface RankedKeywordTargetsForAdGroupRequest extends KeywordTargetRankRecommendationRequest {
    /**
     * The identifier of the campaign
     * @type {string}
     * @memberof RankedKeywordTargetsForAdGroupRequest
     */
    campaignId: string;
    /**
     * The recommendationType to retrieve recommended keyword targets for an existing ad group.
     * @type {string}
     * @memberof RankedKeywordTargetsForAdGroupRequest
     */
    recommendationType: RankedKeywordTargetsForAdGroupRequestRecommendationTypeEnum;
    /**
     * Set this parameter to false if you do not want to retrieve bid suggestions for your keyword targets. Defaults to true.
     * @type {boolean}
     * @memberof RankedKeywordTargetsForAdGroupRequest
     */
    bidsEnabled?: boolean;
    /**
     * The identifier of the ad group
     * @type {string}
     * @memberof RankedKeywordTargetsForAdGroupRequest
     */
    adGroupId: string;
}

/**
    * @export
    * @enum {string}
    */
export enum RankedKeywordTargetsForAdGroupRequestRecommendationTypeEnum {
    KEYWORDSFORADGROUP = 'KEYWORDS_FOR_ADGROUP'
}

