/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImpactMetrics } from './impact-metrics';
import { RankedTargetWithThemedBidsList } from './ranked-target-with-themed-bids-list';
/**
 * 
 * @export
 * @interface RankedTargetWithThemedBidsResponse
 */
export interface RankedTargetWithThemedBidsResponse {
    /**
     * 
     * @type {RankedTargetWithThemedBidsList}
     * @memberof RankedTargetWithThemedBidsResponse
     */
    keywordTargetList?: RankedTargetWithThemedBidsList;
    /**
     * A list of impact metrics which anticipates the number of clicks and orders you will receive if you target all targeting expressions using the low, medium, and high suggested bid.
     * @type {Array<ImpactMetrics>}
     * @memberof RankedTargetWithThemedBidsResponse
     */
    impactMetrics?: Array<ImpactMetrics>;
}
