/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecKeywordTarget } from './rec-keyword-target';
/**
 * 
 * @export
 * @interface RankedTargetResponse
 */
export interface RankedTargetResponse {
    /**
     * A list of ranked keyword targets
     * @type {Array<RecKeywordTarget>}
     * @memberof RankedTargetResponse
     */
    keywordTargetList?: Array<RecKeywordTarget>;
}
