/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgeRangesLoP } from './age-ranges-lo-p';
import { BrandsLoP } from './brands-lo-p';
import { GenresLoP } from './genres-lo-p';
/**
 * Response object for the POST /sp/targets/category/{categoryId}/refinements endpoint, containing information on Brand Nodes, Age Range Nodes, and Genre Nodes.
 * @export
 * @interface RefinementsLoP
 */
export interface RefinementsLoP {
    /**
     * 
     * @type {AgeRangesLoP}
     * @memberof RefinementsLoP
     */
    ageRanges?: AgeRangesLoP;
    /**
     * 
     * @type {BrandsLoP}
     * @memberof RefinementsLoP
     */
    brands?: BrandsLoP;
    /**
     * 
     * @type {GenresLoP}
     * @memberof RefinementsLoP
     */
    genres?: GenresLoP;
}
