/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The action taken when the campaign optimization rule is enabled. Defaults to adopt
 * @export
 * @enum {string}
 */
export enum RuleAction {
    ADOPT = 'ADOPT'
}

