/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CampaignOptimizationId } from './campaign-optimization-id';
import { RuleCampaignId } from './rule-campaign-id';
import { RuleState } from './rule-state';
/**
 * 
 * @export
 * @interface RuleNotification
 */
export interface RuleNotification {
    /**
     * 
     * @type {RuleState}
     * @memberof RuleNotification
     */
    ruleState?: RuleState;
    /**
     * 
     * @type {CampaignOptimizationId}
     * @memberof RuleNotification
     */
    campaignOptimizationId?: CampaignOptimizationId;
    /**
     * 
     * @type {RuleCampaignId}
     * @memberof RuleNotification
     */
    campaignId?: RuleCampaignId;
    /**
     * Explains why the rule state is disabled
     * @type {string}
     * @memberof RuleNotification
     */
    notificationString?: string;
}
