/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Performance Metrics supported by the rule recommendation
 * @export
 * @interface RuleRecommendationMetrics
 */
export interface RuleRecommendationMetrics {
    /**
     * return on ad spend value
     * @type {number}
     * @memberof RuleRecommendationMetrics
     */
    roas?: number;
}
