/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Time of campaign optimization rule creation in ISO 8061. Read-only.
 * @export
 * @interface RuleCreationDate
 */
export interface RuleCreationDate {
}
