/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComparisonOperator } from './comparison-operator';
import { RuleConditionMetric } from './rule-condition-metric';
/**
 * 
 * @export
 * @interface RuleCondition
 */
export interface RuleCondition {
    /**
     * 
     * @type {RuleConditionMetric}
     * @memberof RuleCondition
     */
    metricName: RuleConditionMetric;
    /**
     * 
     * @type {ComparisonOperator}
     * @memberof RuleCondition
     */
    comparisonOperator: ComparisonOperator;
    /**
     * The performance threshold value.
     * @type {number}
     * @memberof RuleCondition
     */
    threshold: number;
}
