/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SpecialEvent
 */
export interface SpecialEvent {
    /**
     * The factor used to boost the recommended budget.
     * @type {number}
     * @memberof SpecialEvent
     */
    budgetModifier?: number;
    /**
     * The end date of the special event in YYYYMMDD format.
     * @type {string}
     * @memberof SpecialEvent
     */
    endDate?: string;
    /**
     * The name of the special event.
     * @type {string}
     * @memberof SpecialEvent
     */
    eventName?: string;
    /**
     * The start date of the special event in YYYYMMDD format.
     * @type {string}
     * @memberof SpecialEvent
     */
    startDate?: string;
}
