/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalCampaignMutationFailureResponseItem } from './sponsored-products-global-campaign-mutation-failure-response-item';
import { SponsoredProductsGlobalCampaignMutationSuccessResponseItem } from './sponsored-products-global-campaign-mutation-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkGlobalCampaignOperationResponse
 */
export interface SponsoredProductsBulkGlobalCampaignOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaignMutationSuccessResponseItem>}
     * @memberof SponsoredProductsBulkGlobalCampaignOperationResponse
     */
    success?: Array<SponsoredProductsGlobalCampaignMutationSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaignMutationFailureResponseItem>}
     * @memberof SponsoredProductsBulkGlobalCampaignOperationResponse
     */
    error?: Array<SponsoredProductsGlobalCampaignMutationFailureResponseItem>;
}
