/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignNegativeKeywordMutationErrorSelector } from './sponsored-products-campaign-negative-keyword-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignNegativeKeywordMutationError
 */
export interface SponsoredProductsCampaignNegativeKeywordMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsCampaignNegativeKeywordMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsCampaignNegativeKeywordMutationErrorSelector}
     * @memberof SponsoredProductsCampaignNegativeKeywordMutationError
     */
    errorValue: SponsoredProductsCampaignNegativeKeywordMutationErrorSelector;
}
