/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDynamicBidding } from './sponsored-products-dynamic-bidding';
import { SponsoredProductsGlobalBudget } from './sponsored-products-global-budget';
import { SponsoredProductsGlobalCampaignExtendedData } from './sponsored-products-global-campaign-extended-data';
import { SponsoredProductsGlobalEntityState } from './sponsored-products-global-entity-state';
import { SponsoredProductsTags } from './sponsored-products-tags';
import { SponsoredProductsTargetingType } from './sponsored-products-targeting-type';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalCampaign
 */
export interface SponsoredProductsGlobalCampaign {
    /**
     * The format of the date is YYYY-MM-DD.
     * @type {string}
     * @memberof SponsoredProductsGlobalCampaign
     */
    endDate?: string;
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsGlobalCampaign
     */
    campaignId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SponsoredProductsGlobalCampaign
     */
    applicableMarketplaces?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SponsoredProductsGlobalCampaign
     */
    name: string;
    /**
     * 
     * @type {SponsoredProductsTargetingType}
     * @memberof SponsoredProductsGlobalCampaign
     */
    targetingType: SponsoredProductsTargetingType;
    /**
     * 
     * @type {SponsoredProductsGlobalEntityState}
     * @memberof SponsoredProductsGlobalCampaign
     */
    state: SponsoredProductsGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsDynamicBidding}
     * @memberof SponsoredProductsGlobalCampaign
     */
    dynamicBidding?: SponsoredProductsDynamicBidding;
    /**
     * The format of the date is YYYY-MM-DD.
     * @type {string}
     * @memberof SponsoredProductsGlobalCampaign
     */
    startDate?: string;
    /**
     * 
     * @type {SponsoredProductsGlobalBudget}
     * @memberof SponsoredProductsGlobalCampaign
     */
    budget: SponsoredProductsGlobalBudget;
    /**
     * 
     * @type {SponsoredProductsTags}
     * @memberof SponsoredProductsGlobalCampaign
     */
    tags?: SponsoredProductsTags;
    /**
     * 
     * @type {SponsoredProductsGlobalCampaignExtendedData}
     * @memberof SponsoredProductsGlobalCampaign
     */
    extendedData?: SponsoredProductsGlobalCampaignExtendedData;
}
