/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignNegativeKeywordExtendedData } from './sponsored-products-campaign-negative-keyword-extended-data';
import { SponsoredProductsEntityState } from './sponsored-products-entity-state';
import { SponsoredProductsNegativeMatchType } from './sponsored-products-negative-match-type';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignNegativeKeyword
 */
export interface SponsoredProductsCampaignNegativeKeyword {
    /**
     * The identifier of the keyword.
     * @type {string}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    keywordId: string;
    /**
     * The identifier of the campaign to which the keyword is associated.
     * @type {string}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsNegativeMatchType}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    matchType: SponsoredProductsNegativeMatchType;
    /**
     * 
     * @type {SponsoredProductsEntityState}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    state: SponsoredProductsEntityState;
    /**
     * The keyword text.
     * @type {string}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    keywordText: string;
    /**
     * 
     * @type {SponsoredProductsCampaignNegativeKeywordExtendedData}
     * @memberof SponsoredProductsCampaignNegativeKeyword
     */
    extendedData?: SponsoredProductsCampaignNegativeKeywordExtendedData;
}
