/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsUnsupportedOperationErrorReason } from './sponsored-products-unsupported-operation-error-reason';
/**
 * Errors being used to represent an unsupported operation e.g. Seller are not supported to create custom text product ads.
 * @export
 * @interface SponsoredProductsUnsupportedOperationError
 */
export interface SponsoredProductsUnsupportedOperationError {
    /**
     * 
     * @type {SponsoredProductsUnsupportedOperationErrorReason}
     * @memberof SponsoredProductsUnsupportedOperationError
     */
    reason: SponsoredProductsUnsupportedOperationErrorReason;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsUnsupportedOperationError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsUnsupportedOperationError
     */
    message: string;
}
