/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsCurrencyErrorReason {
    PREFERREDCURRENCYNOTSET = 'PREFERRED_CURRENCY_NOT_SET',
    CURRENCYNOTSUPPORTED = 'CURRENCY_NOT_SUPPORTED',
    CANNOTUPDATECURRENCY = 'CANNOT_UPDATE_CURRENCY',
    CURRENCYNOTMATCHINGPREFERREDCURRENCY = 'CURRENCY_NOT_MATCHING_PREFERRED_CURRENCY'
}

