/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsNegativeTargetMutationErrorSelector } from './sponsored-products-negative-target-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsNegativeTargetMutationError
 */
export interface SponsoredProductsNegativeTargetMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsNegativeTargetMutationErrorSelector}
     * @memberof SponsoredProductsNegativeTargetMutationError
     */
    errorValue: SponsoredProductsNegativeTargetMutationErrorSelector;
}
