/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignAccessErrorSelector } from './sponsored-products-draft-campaign-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftCampaignAccessError
 */
export interface SponsoredProductsDraftCampaignAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftCampaignAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftCampaignAccessErrorSelector}
     * @memberof SponsoredProductsDraftCampaignAccessError
     */
    errorValue: SponsoredProductsDraftCampaignAccessErrorSelector;
}
