/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsTargetingExpressionPredicateMarketValue } from './sponsored-products-targeting-expression-predicate-market-value';
import { SponsoredProductsTargetingExpressionPredicateType } from './sponsored-products-targeting-expression-predicate-type';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalTargetingExpressionPredicate
 */
export interface SponsoredProductsGlobalTargetingExpressionPredicate {
    /**
     * The marketplace settings for expression to be overridden for marketplace.
     * @type {Array<SponsoredProductsTargetingExpressionPredicateMarketValue>}
     * @memberof SponsoredProductsGlobalTargetingExpressionPredicate
     */
    marketplaceSettings?: Array<SponsoredProductsTargetingExpressionPredicateMarketValue>;
    /**
     * 
     * @type {SponsoredProductsTargetingExpressionPredicateType}
     * @memberof SponsoredProductsGlobalTargetingExpressionPredicate
     */
    type?: SponsoredProductsTargetingExpressionPredicateType;
}
