/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateOrUpdateMarketplaceState
 */
export interface SponsoredProductsCreateOrUpdateMarketplaceState {
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsCreateOrUpdateMarketplaceState
     */
    marketplace: SponsoredProductsMarketplace;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsCreateOrUpdateMarketplaceState
     */
    state: SponsoredProductsCreateOrUpdateEntityState;
}
