/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsAdGroupMutationErrorSelector } from './sponsored-products-ad-group-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsAdGroupMutationError
 */
export interface SponsoredProductsAdGroupMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsAdGroupMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsAdGroupMutationErrorSelector}
     * @memberof SponsoredProductsAdGroupMutationError
     */
    errorValue: SponsoredProductsAdGroupMutationErrorSelector;
}
