/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsMarketplaceBudget
 */
export interface SponsoredProductsMarketplaceBudget {
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsMarketplaceBudget
     */
    marketplace?: SponsoredProductsMarketplace;
    /**
     * Monetary value
     * @type {number}
     * @memberof SponsoredProductsMarketplaceBudget
     */
    budget: number;
}
