/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityType } from './sponsored-products-entity-type';
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsQuotaErrorReason } from './sponsored-products-quota-error-reason';
import { SponsoredProductsQuotaScope } from './sponsored-products-quota-scope';
/**
 * Errors related to exceeding quota in campaign management service
 * @export
 * @interface SponsoredProductsEntityQuotaError
 */
export interface SponsoredProductsEntityQuotaError {
    /**
     * 
     * @type {SponsoredProductsQuotaErrorReason}
     * @memberof SponsoredProductsEntityQuotaError
     */
    reason: SponsoredProductsQuotaErrorReason;
    /**
     * 
     * @type {SponsoredProductsQuotaScope}
     * @memberof SponsoredProductsEntityQuotaError
     */
    quotaScope?: SponsoredProductsQuotaScope;
    /**
     * 
     * @type {SponsoredProductsEntityType}
     * @memberof SponsoredProductsEntityQuotaError
     */
    entityType: SponsoredProductsEntityType;
    /**
     * optional current quota
     * @type {string}
     * @memberof SponsoredProductsEntityQuotaError
     */
    quota?: string;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsEntityQuotaError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsEntityQuotaError
     */
    message: string;
}
