/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Filter entities by the list of objectIds
 * @export
 * @interface SponsoredProductsObjectIdFilter
 */
export interface SponsoredProductsObjectIdFilter {
    /**
     * 
     * @type {Array<string>}
     * @memberof SponsoredProductsObjectIdFilter
     */
    include: Array<string>;
}
