/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignMutationError } from './sponsored-products-campaign-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignMutationFailureResponseItem
 */
export interface SponsoredProductsCampaignMutationFailureResponseItem {
    /**
     * the index of the campaign in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsCampaignMutationFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsCampaignMutationError>}
     * @memberof SponsoredProductsCampaignMutationFailureResponseItem
     */
    errors?: Array<SponsoredProductsCampaignMutationError>;
}
