/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftNegativeKeywordMutationError } from './sponsored-products-draft-negative-keyword-mutation-error';
import { SponsoredProductsInvalidArgumentErrorCode } from './sponsored-products-invalid-argument-error-code';
/**
 * Exception resulting in mutating campaign management entities
 * @export
 * @interface SponsoredProductsDraftNegativeKeywordMutationExceptionResponseContent
 */
export interface SponsoredProductsDraftNegativeKeywordMutationExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsInvalidArgumentErrorCode}
     * @memberof SponsoredProductsDraftNegativeKeywordMutationExceptionResponseContent
     */
    code: SponsoredProductsInvalidArgumentErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsDraftNegativeKeywordMutationExceptionResponseContent
     */
    message: string;
    /**
     * 
     * @type {Array<SponsoredProductsDraftNegativeKeywordMutationError>}
     * @memberof SponsoredProductsDraftNegativeKeywordMutationExceptionResponseContent
     */
    errors?: Array<SponsoredProductsDraftNegativeKeywordMutationError>;
}
