/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsInvalidArgumentErrorCode } from './sponsored-products-invalid-argument-error-code';
import { SponsoredProductsKeywordMutationError } from './sponsored-products-keyword-mutation-error';
/**
 * Exception resulting in mutating campaign management entities
 * @export
 * @interface SponsoredProductsKeywordMutationExceptionResponseContent
 */
export interface SponsoredProductsKeywordMutationExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsInvalidArgumentErrorCode}
     * @memberof SponsoredProductsKeywordMutationExceptionResponseContent
     */
    code: SponsoredProductsInvalidArgumentErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsKeywordMutationExceptionResponseContent
     */
    message: string;
    /**
     * 
     * @type {Array<SponsoredProductsKeywordMutationError>}
     * @memberof SponsoredProductsKeywordMutationExceptionResponseContent
     */
    errors?: Array<SponsoredProductsKeywordMutationError>;
}
