/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateTargetingExpressionPredicateType } from './sponsored-products-create-targeting-expression-predicate-type';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateTargetingExpressionPredicate
 */
export interface SponsoredProductsCreateTargetingExpressionPredicate {
    /**
     * 
     * @type {SponsoredProductsCreateTargetingExpressionPredicateType}
     * @memberof SponsoredProductsCreateTargetingExpressionPredicate
     */
    type: SponsoredProductsCreateTargetingExpressionPredicateType;
    /**
     * The expression value
     * @type {string}
     * @memberof SponsoredProductsCreateTargetingExpressionPredicate
     */
    value?: string;
}
