/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsNegativeTargetingExpressionPredicateType } from './sponsored-products-negative-targeting-expression-predicate-type';
/**
 * 
 * @export
 * @interface SponsoredProductsNegativeTargetingExpressionPredicate
 */
export interface SponsoredProductsNegativeTargetingExpressionPredicate {
    /**
     * 
     * @type {SponsoredProductsNegativeTargetingExpressionPredicateType}
     * @memberof SponsoredProductsNegativeTargetingExpressionPredicate
     */
    type?: SponsoredProductsNegativeTargetingExpressionPredicateType;
    /**
     * The expression value
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetingExpressionPredicate
     */
    value?: string;
}
