/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignNegativeKeyword } from './sponsored-products-draft-campaign-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsDraftCampaignNegativeKeywordsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsDraftCampaignNegativeKeywordsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignNegativeKeywordsResponseContent
     */
    totalResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignNegativeKeywordsResponseContent
     */
    nextToken?: string;
    /**
     * 
     * @type {Array<SponsoredProductsDraftCampaignNegativeKeyword>}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignNegativeKeywordsResponseContent
     */
    campaignNegativeKeywords?: Array<SponsoredProductsDraftCampaignNegativeKeyword>;
}
