/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsMarketplaceLevelProductIdentifier
 */
export interface SponsoredProductsMarketplaceLevelProductIdentifier {
    /**
     * 
     * @type {string}
     * @memberof SponsoredProductsMarketplaceLevelProductIdentifier
     */
    identifier: string;
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsMarketplaceLevelProductIdentifier
     */
    marketplace?: SponsoredProductsMarketplace;
}
