/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkDraftTargetingClauseOperationResponse } from './sponsored-products-bulk-draft-targeting-clause-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsDraftTargetingClausesResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsDraftTargetingClausesResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkDraftTargetingClauseOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsDraftTargetingClausesResponseContent
     */
    targetingClauses: SponsoredProductsBulkDraftTargetingClauseOperationResponse;
}
