/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftTargetMutationError } from './sponsored-products-draft-target-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftTargetingClauseFailureResponseItem
 */
export interface SponsoredProductsDraftTargetingClauseFailureResponseItem {
    /**
     * the index of the draftTargetingClause in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftTargetingClauseFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsDraftTargetMutationError>}
     * @memberof SponsoredProductsDraftTargetingClauseFailureResponseItem
     */
    errors?: Array<SponsoredProductsDraftTargetMutationError>;
}
