/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsObjectIdFilter } from './sponsored-products-object-id-filter';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsGlobalTargetingClausesRequestContent
 */
export interface SponsoredProductsDeleteSponsoredProductsGlobalTargetingClausesRequestContent {
    /**
     * 
     * @type {SponsoredProductsObjectIdFilter}
     * @memberof SponsoredProductsDeleteSponsoredProductsGlobalTargetingClausesRequestContent
     */
    targetIdFilter?: SponsoredProductsObjectIdFilter;
}
