/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftKeywordMutationError } from './sponsored-products-draft-keyword-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftKeywordFailureResponseItem
 */
export interface SponsoredProductsDraftKeywordFailureResponseItem {
    /**
     * the index of the draft keyword in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftKeywordFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsDraftKeywordMutationError>}
     * @memberof SponsoredProductsDraftKeywordFailureResponseItem
     */
    errors?: Array<SponsoredProductsDraftKeywordMutationError>;
}
