// Custom patch
interface GenericStringMap {
  [key: string]: string;
}

/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A list of advertiser-specified custom identifiers for the campaign. Each customer identifier is a key-value pair. You can specify a maximum of 50 identifiers.
 * @export
 * @interface SponsoredProductsTags
 */
export interface SponsoredProductsTags extends GenericStringMap {}
