/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateAdGroup
 */
export interface SponsoredProductsUpdateAdGroup {
    /**
     * The name of the ad group.
     * @type {string}
     * @memberof SponsoredProductsUpdateAdGroup
     */
    name: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsUpdateAdGroup
     */
    state: SponsoredProductsCreateOrUpdateEntityState;
    /**
     * The identifier of the keyword.
     * @type {string}
     * @memberof SponsoredProductsUpdateAdGroup
     */
    adGroupId: string;
    /**
     * A bid value for use when no bid is specified for keywords in the ad group. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsUpdateAdGroup
     */
    defaultBid: number;
}
