/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftProductAdMutationErrorSelector } from './sponsored-products-draft-product-ad-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftProductAdMutationError
 */
export interface SponsoredProductsDraftProductAdMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftProductAdMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftProductAdMutationErrorSelector}
     * @memberof SponsoredProductsDraftProductAdMutationError
     */
    errorValue: SponsoredProductsDraftProductAdMutationErrorSelector;
}
