/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityStateErrorReason } from './sponsored-products-entity-state-error-reason';
import { SponsoredProductsEntityType } from './sponsored-products-entity-type';
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * entity state update errors
 * @export
 * @interface SponsoredProductsEntityStateError
 */
export interface SponsoredProductsEntityStateError {
    /**
     * 
     * @type {SponsoredProductsEntityStateErrorReason}
     * @memberof SponsoredProductsEntityStateError
     */
    reason: SponsoredProductsEntityStateErrorReason;
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsEntityStateError
     */
    marketplace?: SponsoredProductsMarketplace;
    /**
     * 
     * @type {SponsoredProductsEntityType}
     * @memberof SponsoredProductsEntityStateError
     */
    entityType: SponsoredProductsEntityType;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsEntityStateError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsEntityStateError
     */
    message: string;
}
