/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftNegativeTargetMutationErrorSelector } from './sponsored-products-draft-negative-target-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftNegativeTargetMutationError
 */
export interface SponsoredProductsDraftNegativeTargetMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftNegativeTargetMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftNegativeTargetMutationErrorSelector}
     * @memberof SponsoredProductsDraftNegativeTargetMutationError
     */
    errorValue: SponsoredProductsDraftNegativeTargetMutationErrorSelector;
}
