/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftAdGroupAccessErrorSelector } from './sponsored-products-draft-ad-group-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftAdGroupAccessError
 */
export interface SponsoredProductsDraftAdGroupAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftAdGroupAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftAdGroupAccessErrorSelector}
     * @memberof SponsoredProductsDraftAdGroupAccessError
     */
    errorValue: SponsoredProductsDraftAdGroupAccessErrorSelector;
}
