/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsLocaleErrorReason } from './sponsored-products-locale-error-reason';
/**
 * 
 * @export
 * @interface SponsoredProductsLocaleError
 */
export interface SponsoredProductsLocaleError {
    /**
     * 
     * @type {SponsoredProductsLocaleErrorReason}
     * @memberof SponsoredProductsLocaleError
     */
    reason: SponsoredProductsLocaleErrorReason;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsLocaleError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsLocaleError
     */
    message: string;
}
