/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsTargetingExpressionPredicateType } from './sponsored-products-targeting-expression-predicate-type';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetingExpressionPredicate
 */
export interface SponsoredProductsTargetingExpressionPredicate {
    /**
     * 
     * @type {SponsoredProductsTargetingExpressionPredicateType}
     * @memberof SponsoredProductsTargetingExpressionPredicate
     */
    type?: SponsoredProductsTargetingExpressionPredicateType;
    /**
     * The expression value
     * @type {string}
     * @memberof SponsoredProductsTargetingExpressionPredicate
     */
    value?: string;
}
