/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftProductAdFailureResponseItem } from './sponsored-products-draft-product-ad-failure-response-item';
import { SponsoredProductsDraftProductAdSuccessResponseItem } from './sponsored-products-draft-product-ad-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkDraftProductAdOperationResponse
 */
export interface SponsoredProductsBulkDraftProductAdOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsDraftProductAdSuccessResponseItem>}
     * @memberof SponsoredProductsBulkDraftProductAdOperationResponse
     */
    success?: Array<SponsoredProductsDraftProductAdSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsDraftProductAdFailureResponseItem>}
     * @memberof SponsoredProductsBulkDraftProductAdOperationResponse
     */
    error?: Array<SponsoredProductsDraftProductAdFailureResponseItem>;
}
