/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkGlobalKeywordOperationResponse } from './sponsored-products-bulk-global-keyword-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
 */
export interface SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkGlobalKeywordOperationResponse}
     * @memberof SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
     */
    keywords: SponsoredProductsBulkGlobalKeywordOperationResponse;
}
