/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalAdGroup } from './sponsored-products-global-ad-group';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalAdGroupSuccessResponseItem
 */
export interface SponsoredProductsGlobalAdGroupSuccessResponseItem {
    /**
     * 
     * @type {SponsoredProductsGlobalAdGroup}
     * @memberof SponsoredProductsGlobalAdGroupSuccessResponseItem
     */
    adGroup?: SponsoredProductsGlobalAdGroup;
    /**
     * the index of the adGroup in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsGlobalAdGroupSuccessResponseItem
     */
    index: number;
    /**
     * the adGroup ID
     * @type {string}
     * @memberof SponsoredProductsGlobalAdGroupSuccessResponseItem
     */
    adGroupId?: string;
}
