/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsQueryTermMatchType } from './sponsored-products-query-term-match-type';
/**
 * 
 * @export
 * @interface SponsoredProductsAsinFilter
 */
export interface SponsoredProductsAsinFilter {
    /**
     * 
     * @type {SponsoredProductsQueryTermMatchType}
     * @memberof SponsoredProductsAsinFilter
     */
    queryTermMatchType?: SponsoredProductsQueryTermMatchType;
    /**
     * 
     * @type {Array<string>}
     * @memberof SponsoredProductsAsinFilter
     */
    include?: Array<string>;
}
