/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsNegativeMatchType {
    NEGATIVEEXACT = 'NEGATIVE_EXACT',
    NEGATIVEPHRASE = 'NEGATIVE_PHRASE',
    NEGATIVEBROAD = 'NEGATIVE_BROAD',
    OTHER = 'OTHER'
}

