/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkGlobalNegativeKeywordOperationResponse } from './sponsored-products-bulk-global-negative-keyword-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsResponseContent
 */
export interface SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkGlobalNegativeKeywordOperationResponse}
     * @memberof SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsResponseContent
     */
    negativeKeywords: SponsoredProductsBulkGlobalNegativeKeywordOperationResponse;
}
