/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignPromotionStatus } from './sponsored-products-draft-campaign-promotion-status';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsDraftCampaignsPromotionStatusResponseContent
 */
export interface SponsoredProductsListSponsoredProductsDraftCampaignsPromotionStatusResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignsPromotionStatusResponseContent
     */
    totalResults?: number;
    /**
     * 
     * @type {Array<SponsoredProductsDraftCampaignPromotionStatus>}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignsPromotionStatusResponseContent
     */
    campaignStatuses?: Array<SponsoredProductsDraftCampaignPromotionStatus>;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsDraftCampaignsPromotionStatusResponseContent
     */
    nextToken?: string;
}
