/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignNegativeKeywordMutationErrorSelector } from './sponsored-products-draft-campaign-negative-keyword-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftCampaignNegativeKeywordMutationError
 */
export interface SponsoredProductsDraftCampaignNegativeKeywordMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftCampaignNegativeKeywordMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftCampaignNegativeKeywordMutationErrorSelector}
     * @memberof SponsoredProductsDraftCampaignNegativeKeywordMutationError
     */
    errorValue: SponsoredProductsDraftCampaignNegativeKeywordMutationErrorSelector;
}
