/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDateErrorReason } from './sponsored-products-date-error-reason';
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
/**
 * 
 * @export
 * @interface SponsoredProductsDateError
 */
export interface SponsoredProductsDateError {
    /**
     * 
     * @type {SponsoredProductsDateErrorReason}
     * @memberof SponsoredProductsDateError
     */
    reason: SponsoredProductsDateErrorReason;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsDateError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsDateError
     */
    message: string;
}
