/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignNegativeKeywordAccessErrorSelector } from './sponsored-products-draft-campaign-negative-keyword-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftCampaignNegativeKeywordAccessError
 */
export interface SponsoredProductsDraftCampaignNegativeKeywordAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftCampaignNegativeKeywordAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftCampaignNegativeKeywordAccessErrorSelector}
     * @memberof SponsoredProductsDraftCampaignNegativeKeywordAccessError
     */
    errorValue: SponsoredProductsDraftCampaignNegativeKeywordAccessErrorSelector;
}
