/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsInvalidArgumentErrorCode } from './sponsored-products-invalid-argument-error-code';
import { SponsoredProductsKeywordAccessError } from './sponsored-products-keyword-access-error';
/**
 * Exception resulting in accessing campaign management entities
 * @export
 * @interface SponsoredProductsKeywordAccessExceptionResponseContent
 */
export interface SponsoredProductsKeywordAccessExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsInvalidArgumentErrorCode}
     * @memberof SponsoredProductsKeywordAccessExceptionResponseContent
     */
    code: SponsoredProductsInvalidArgumentErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsKeywordAccessExceptionResponseContent
     */
    message: string;
    /**
     * 
     * @type {Array<SponsoredProductsKeywordAccessError>}
     * @memberof SponsoredProductsKeywordAccessExceptionResponseContent
     */
    errors?: Array<SponsoredProductsKeywordAccessError>;
}
