/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignNegativeTargetsAccessErrorSelector } from './sponsored-products-campaign-negative-targets-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignNegativeTargetsAccessError
 */
export interface SponsoredProductsCampaignNegativeTargetsAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsCampaignNegativeTargetsAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsCampaignNegativeTargetsAccessErrorSelector}
     * @memberof SponsoredProductsCampaignNegativeTargetsAccessError
     */
    errorValue: SponsoredProductsCampaignNegativeTargetsAccessErrorSelector;
}
