/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsAdGroupFailureResponseItem } from './sponsored-products-ad-group-failure-response-item';
import { SponsoredProductsAdGroupSuccessResponseItem } from './sponsored-products-ad-group-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkAdGroupOperationResponse
 */
export interface SponsoredProductsBulkAdGroupOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsAdGroupSuccessResponseItem>}
     * @memberof SponsoredProductsBulkAdGroupOperationResponse
     */
    success?: Array<SponsoredProductsAdGroupSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsAdGroupFailureResponseItem>}
     * @memberof SponsoredProductsBulkAdGroupOperationResponse
     */
    error?: Array<SponsoredProductsAdGroupFailureResponseItem>;
}
