/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkProductAdOperationResponse } from './sponsored-products-bulk-product-ad-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkProductAdOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent
     */
    productAds: SponsoredProductsBulkProductAdOperationResponse;
}
