/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateCampaignNegativeTargetingClause } from './sponsored-products-update-campaign-negative-targeting-clause';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsCampaignNegativeTargetingClausesRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsCampaignNegativeTargetingClausesRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateCampaignNegativeTargetingClause>}
     * @memberof SponsoredProductsUpdateSponsoredProductsCampaignNegativeTargetingClausesRequestContent
     */
    campaignNegativeTargetingClauses: Array<SponsoredProductsUpdateCampaignNegativeTargetingClause>;
}
