/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeyword } from './sponsored-products-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsKeywordSuccessResponseItem
 */
export interface SponsoredProductsKeywordSuccessResponseItem {
    /**
     * the keyword ID
     * @type {string}
     * @memberof SponsoredProductsKeywordSuccessResponseItem
     */
    keywordId?: string;
    /**
     * the index of the keyword in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsKeywordSuccessResponseItem
     */
    index: number;
    /**
     * 
     * @type {SponsoredProductsKeyword}
     * @memberof SponsoredProductsKeywordSuccessResponseItem
     */
    keyword?: SponsoredProductsKeyword;
}
