/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsGlobalCampaignMarketplaceServingStatus {
    CAMPAIGNSTATUSENABLED = 'CAMPAIGN_STATUS_ENABLED',
    CAMPAIGNPAUSED = 'CAMPAIGN_PAUSED',
    CAMPAIGNARCHIVED = 'CAMPAIGN_ARCHIVED',
    PENDINGREVIEW = 'PENDING_REVIEW',
    REJECTED = 'REJECTED',
    PENDINGSTARTDATE = 'PENDING_START_DATE',
    ENDED = 'ENDED',
    CAMPAIGNOUTOFBUDGET = 'CAMPAIGN_OUT_OF_BUDGET',
    CAMPAIGNINCOMPLETE = 'CAMPAIGN_INCOMPLETE',
    ADVERTISERPOLICINGSUSPENDED = 'ADVERTISER_POLICING_SUSPENDED',
    ADVERTISERPOLICINGPENDINGREVIEW = 'ADVERTISER_POLICING_PENDING_REVIEW',
    ADVERTISERARCHIVED = 'ADVERTISER_ARCHIVED',
    ADVERTISERPAUSED = 'ADVERTISER_PAUSED',
    ADVERTISERPAYMENTFAILURE = 'ADVERTISER_PAYMENT_FAILURE'
}

