/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftProductAdExtendedData } from './sponsored-products-draft-product-ad-extended-data';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftProductAd
 */
export interface SponsoredProductsDraftProductAd {
    /**
     * The product ad identifier.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    adId: string;
    /**
     * The campaign identifier.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    campaignId: string;
    /**
     * The custom text that is associated with this ad. Defined for custom text ads only.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    customText?: string;
    /**
     * The ASIN associated with the product. Defined for vendors only.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    asin?: string;
    /**
     * The SKU associated with the product. Defined for seller accounts only.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    sku?: string;
    /**
     * The ad group identifier.
     * @type {string}
     * @memberof SponsoredProductsDraftProductAd
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsDraftProductAdExtendedData}
     * @memberof SponsoredProductsDraftProductAd
     */
    extendedData?: SponsoredProductsDraftProductAdExtendedData;
}
