/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftNegativeTargetMutationError } from './sponsored-products-draft-negative-target-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftNegativeTargetingClauseFailureResponseItem
 */
export interface SponsoredProductsDraftNegativeTargetingClauseFailureResponseItem {
    /**
     * the index of the DraftNegativeTargetingClause in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftNegativeTargetingClauseFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsDraftNegativeTargetMutationError>}
     * @memberof SponsoredProductsDraftNegativeTargetingClauseFailureResponseItem
     */
    errors?: Array<SponsoredProductsDraftNegativeTargetMutationError>;
}
