/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsExpressionType } from './sponsored-products-expression-type';
/**
 * Filter entities by ExpressionType
 * @export
 * @interface SponsoredProductsExpressionTypeFilter
 */
export interface SponsoredProductsExpressionTypeFilter {
    /**
     * 
     * @type {Array<SponsoredProductsExpressionType>}
     * @memberof SponsoredProductsExpressionTypeFilter
     */
    include: Array<SponsoredProductsExpressionType>;
}
