/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsAdGroupServingStatusReason } from './sponsored-products-ad-group-serving-status-reason';
/**
 * 
 * @export
 * @interface SponsoredProductsAdGroupServingStatusDetail
 */
export interface SponsoredProductsAdGroupServingStatusDetail {
    /**
     * 
     * @type {SponsoredProductsAdGroupServingStatusReason}
     * @memberof SponsoredProductsAdGroupServingStatusDetail
     */
    name?: SponsoredProductsAdGroupServingStatusReason;
    /**
     * A URL with additional information about the status identifier.
     * @type {string}
     * @memberof SponsoredProductsAdGroupServingStatusDetail
     */
    helpUrl?: string;
    /**
     * A human-readable description of the status identifier specified in the name field.
     * @type {string}
     * @memberof SponsoredProductsAdGroupServingStatusDetail
     */
    message?: string;
}
