/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsEntityType {
    CAMPAIGN = 'CAMPAIGN',
    ADGROUP = 'AD_GROUP',
    KEYWORD = 'KEYWORD',
    PRODUCTAD = 'PRODUCT_AD',
    CAMPAIGNNEGATIVEKEYWORD = 'CAMPAIGN_NEGATIVE_KEYWORD',
    NEGATIVEKEYWORD = 'NEGATIVE_KEYWORD',
    TARGETINGCLAUSE = 'TARGETING_CLAUSE',
    NEGATIVETARGETINGCLAUSE = 'NEGATIVE_TARGETING_CLAUSE',
    CAMPAIGNNEGATIVETARGETINGCLAUSE = 'CAMPAIGN_NEGATIVE_TARGETING_CLAUSE'
}

