/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsParentEntityErrorReason {
    DOESNOTTARGETTHESEMARKETPLACES = 'PARENT_ENTITY_DOES_NOT_TARGET_THESE_MARKETPLACES',
    ARCHIVED = 'PARENT_ENTITY_ARCHIVED',
    NOTFOUND = 'PARENT_ENTITY_NOT_FOUND'
}

