/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateNegativeKeyword } from './sponsored-products-update-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsNegativeKeywordsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsNegativeKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateNegativeKeyword>}
     * @memberof SponsoredProductsUpdateSponsoredProductsNegativeKeywordsRequestContent
     */
    negativeKeywords: Array<SponsoredProductsUpdateNegativeKeyword>;
}
