/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
import { SponsoredProductsCreateOrUpdateNegativeTargetingExpressionPredicate } from './sponsored-products-create-or-update-negative-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateCampaignNegativeTargetingClause
 */
export interface SponsoredProductsUpdateCampaignNegativeTargetingClause {
    /**
     * The NegativeTargeting expression.
     * @type {Array<SponsoredProductsCreateOrUpdateNegativeTargetingExpressionPredicate>}
     * @memberof SponsoredProductsUpdateCampaignNegativeTargetingClause
     */
    expression?: Array<SponsoredProductsCreateOrUpdateNegativeTargetingExpressionPredicate>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsUpdateCampaignNegativeTargetingClause
     */
    targetId: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsUpdateCampaignNegativeTargetingClause
     */
    state?: SponsoredProductsCreateOrUpdateEntityState;
}
