/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateDraftNegativeKeyword } from './sponsored-products-create-draft-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsDraftNegativeKeywordsRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsDraftNegativeKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsCreateDraftNegativeKeyword>}
     * @memberof SponsoredProductsCreateSponsoredProductsDraftNegativeKeywordsRequestContent
     */
    negativeKeywords: Array<SponsoredProductsCreateDraftNegativeKeyword>;
}
