/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsTargetingExpressionPredicateTypeWithoutOther } from './sponsored-products-targeting-expression-predicate-type-without-other';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetingExpressionPredicateWithoutOther
 */
export interface SponsoredProductsTargetingExpressionPredicateWithoutOther {
    /**
     * 
     * @type {SponsoredProductsTargetingExpressionPredicateTypeWithoutOther}
     * @memberof SponsoredProductsTargetingExpressionPredicateWithoutOther
     */
    type: SponsoredProductsTargetingExpressionPredicateTypeWithoutOther;
    /**
     * The expression value
     * @type {string}
     * @memberof SponsoredProductsTargetingExpressionPredicateWithoutOther
     */
    value?: string;
}
