/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeywordTextMarketplaceSettings } from './sponsored-products-keyword-text-marketplace-settings';
import { SponsoredProductsLocale } from './sponsored-products-locale';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalKeywordText
 */
export interface SponsoredProductsGlobalKeywordText {
    /**
     * The marketplace settings for keyword text to be overridden for marketplace.
     * @type {Array<SponsoredProductsKeywordTextMarketplaceSettings>}
     * @memberof SponsoredProductsGlobalKeywordText
     */
    marketplaceSettings?: Array<SponsoredProductsKeywordTextMarketplaceSettings>;
    /**
     * 
     * @type {SponsoredProductsLocale}
     * @memberof SponsoredProductsGlobalKeywordText
     */
    locale?: SponsoredProductsLocale;
    /**
     * 
     * @type {string}
     * @memberof SponsoredProductsGlobalKeywordText
     */
    value: string;
}
