/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateExpressionType } from './sponsored-products-create-expression-type';
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
import { SponsoredProductsCreateTargetingExpressionPredicate } from './sponsored-products-create-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateTargetingClause
 */
export interface SponsoredProductsCreateTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsCreateTargetingExpressionPredicate>}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    expression: Array<SponsoredProductsCreateTargetingExpressionPredicate>;
    /**
     * The identifier of the campaign to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsCreateExpressionType}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    expressionType: SponsoredProductsCreateExpressionType;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    state: SponsoredProductsCreateOrUpdateEntityState;
    /**
     * The bid for ads sourced using the target. Targets that do not have bid values in listTargetingClauses will inherit the defaultBid from the adGroup level. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    bid?: number | null;
    /**
     * The identifier of the ad group to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateTargetingClause
     */
    adGroupId: string;
}
