/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftKeyword } from './sponsored-products-draft-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftKeywordSuccessResponseItem
 */
export interface SponsoredProductsDraftKeywordSuccessResponseItem {
    /**
     * the draft keyword ID
     * @type {string}
     * @memberof SponsoredProductsDraftKeywordSuccessResponseItem
     */
    keywordId?: string;
    /**
     * the index of the draft keyword in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftKeywordSuccessResponseItem
     */
    index: number;
    /**
     * 
     * @type {SponsoredProductsDraftKeyword}
     * @memberof SponsoredProductsDraftKeywordSuccessResponseItem
     */
    keyword?: SponsoredProductsDraftKeyword;
}
