/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftKeywordFailureResponseItem } from './sponsored-products-draft-keyword-failure-response-item';
import { SponsoredProductsDraftKeywordSuccessResponseItem } from './sponsored-products-draft-keyword-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkDraftKeywordOperationResponse
 */
export interface SponsoredProductsBulkDraftKeywordOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsDraftKeywordSuccessResponseItem>}
     * @memberof SponsoredProductsBulkDraftKeywordOperationResponse
     */
    success?: Array<SponsoredProductsDraftKeywordSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsDraftKeywordFailureResponseItem>}
     * @memberof SponsoredProductsBulkDraftKeywordOperationResponse
     */
    error?: Array<SponsoredProductsDraftKeywordFailureResponseItem>;
}
