/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalEntityState } from './sponsored-products-global-entity-state';
import { SponsoredProductsGlobalNegativeKeywordExtendedData } from './sponsored-products-global-negative-keyword-extended-data';
import { SponsoredProductsGlobalNegativeKeywordText } from './sponsored-products-global-negative-keyword-text';
import { SponsoredProductsNegativeMatchType } from './sponsored-products-negative-match-type';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalNegativeKeyword
 */
export interface SponsoredProductsGlobalNegativeKeyword {
    /**
     * The identifier of the keyword.
     * @type {string}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    keywordId: string;
    /**
     * The identifier of the campaign to which the keyword is associated.
     * @type {string}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsNegativeMatchType}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    matchType: SponsoredProductsNegativeMatchType;
    /**
     * Name for the keyword
     * @type {string}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsGlobalEntityState}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    state: SponsoredProductsGlobalEntityState;
    /**
     * The identifier of the ad group to which this keyword is associated.
     * @type {string}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsGlobalNegativeKeywordText}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    keywordText: SponsoredProductsGlobalNegativeKeywordText;
    /**
     * 
     * @type {SponsoredProductsGlobalNegativeKeywordExtendedData}
     * @memberof SponsoredProductsGlobalNegativeKeyword
     */
    extendedData?: SponsoredProductsGlobalNegativeKeywordExtendedData;
}
