/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkDraftAdGroupOperationResponse } from './sponsored-products-bulk-draft-ad-group-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsDraftAdGroupsResponseContent
 */
export interface SponsoredProductsCreateSponsoredProductsDraftAdGroupsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkDraftAdGroupOperationResponse}
     * @memberof SponsoredProductsCreateSponsoredProductsDraftAdGroupsResponseContent
     */
    adGroups: SponsoredProductsBulkDraftAdGroupOperationResponse;
}
