/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
import { SponsoredProductsCreateOrUpdateMatchType } from './sponsored-products-create-or-update-match-type';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateKeyword
 */
export interface SponsoredProductsCreateKeyword {
    /**
     * The unlocalized keyword text in the preferred locale of the advertiser.
     * @type {string}
     * @memberof SponsoredProductsCreateKeyword
     */
    nativeLanguageKeyword?: string;
    /**
     * The locale preference of the advertiser. For example, if the advertiser’s preferred language is Simplified Chinese, set the locale to zh_CN. Supported locales include: Simplified Chinese (locale: zh_CN) for US, UK and CA. English (locale: en_GB) for DE, FR, IT and ES.
     * @type {string}
     * @memberof SponsoredProductsCreateKeyword
     */
    nativeLanguageLocale?: string;
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsCreateKeyword
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateMatchType}
     * @memberof SponsoredProductsCreateKeyword
     */
    matchType: SponsoredProductsCreateOrUpdateMatchType;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsCreateKeyword
     */
    state: SponsoredProductsCreateOrUpdateEntityState;
    /**
     * Bid associated with this keyword. Applicable to biddable match types only. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsCreateKeyword
     */
    bid?: number | null;
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsCreateKeyword
     */
    adGroupId: string;
    /**
     * 
     * @type {string}
     * @memberof SponsoredProductsCreateKeyword
     */
    keywordText: string;
}
