/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeywordServingStatus } from './sponsored-products-keyword-serving-status';
import { SponsoredProductsKeywordServingStatusDetail } from './sponsored-products-keyword-serving-status-detail';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignNegativeKeywordExtendedData
 */
export interface SponsoredProductsCampaignNegativeKeywordExtendedData {
    /**
     * Last updated date in ISO 8601.
     * @type {Date}
     * @memberof SponsoredProductsCampaignNegativeKeywordExtendedData
     */
    lastUpdateDateTime?: Date;
    /**
     * 
     * @type {SponsoredProductsKeywordServingStatus}
     * @memberof SponsoredProductsCampaignNegativeKeywordExtendedData
     */
    servingStatus?: SponsoredProductsKeywordServingStatus;
    /**
     * The serving status reasons of the Keyword
     * @type {Array<SponsoredProductsKeywordServingStatusDetail>}
     * @memberof SponsoredProductsCampaignNegativeKeywordExtendedData
     */
    servingStatusDetails?: Array<SponsoredProductsKeywordServingStatusDetail>;
    /**
     * Creation date in ISO 8601.
     * @type {Date}
     * @memberof SponsoredProductsCampaignNegativeKeywordExtendedData
     */
    creationDateTime?: Date;
}
