/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsInvalidArgumentErrorCode } from './sponsored-products-invalid-argument-error-code';
import { SponsoredProductsTargetMutationError } from './sponsored-products-target-mutation-error';
/**
 * Exception resulting in mutating campaign management entities
 * @export
 * @interface SponsoredProductsTargetMutationExceptionResponseContent
 */
export interface SponsoredProductsTargetMutationExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsInvalidArgumentErrorCode}
     * @memberof SponsoredProductsTargetMutationExceptionResponseContent
     */
    code: SponsoredProductsInvalidArgumentErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsTargetMutationExceptionResponseContent
     */
    message: string;
    /**
     * 
     * @type {Array<SponsoredProductsTargetMutationError>}
     * @memberof SponsoredProductsTargetMutationExceptionResponseContent
     */
    errors?: Array<SponsoredProductsTargetMutationError>;
}
