/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsExpressionTypeWithoutOther } from './sponsored-products-expression-type-without-other';
import { SponsoredProductsGlobalBid } from './sponsored-products-global-bid';
import { SponsoredProductsGlobalTargetingExpressionPredicate } from './sponsored-products-global-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateGlobalTargetingClause
 */
export interface SponsoredProductsUpdateGlobalTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsGlobalTargetingExpressionPredicate>}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    expression?: Array<SponsoredProductsGlobalTargetingExpressionPredicate>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    targetId: string;
    /**
     * Name for the targeting clause
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsExpressionTypeWithoutOther}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    expressionType?: SponsoredProductsExpressionTypeWithoutOther;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    state?: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalBid}
     * @memberof SponsoredProductsUpdateGlobalTargetingClause
     */
    bid?: SponsoredProductsGlobalBid;
}
