/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCopyCampaignTaskDetails } from './sponsored-products-copy-campaign-task-details';
/**
 * 
 * @export
 * @interface SponsoredProductsCopySponsoredProductsCampaignsStatusResponseContent
 */
export interface SponsoredProductsCopySponsoredProductsCampaignsStatusResponseContent {
    /**
     * 
     * @type {SponsoredProductsCopyCampaignTaskDetails}
     * @memberof SponsoredProductsCopySponsoredProductsCampaignsStatusResponseContent
     */
    asyncTaskDetail: SponsoredProductsCopyCampaignTaskDetails;
}
