/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftProductAdMutationError } from './sponsored-products-draft-product-ad-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftProductAdFailureResponseItem
 */
export interface SponsoredProductsDraftProductAdFailureResponseItem {
    /**
     * the index of the campaign in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftProductAdFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsDraftProductAdMutationError>}
     * @memberof SponsoredProductsDraftProductAdFailureResponseItem
     */
    errors?: Array<SponsoredProductsDraftProductAdMutationError>;
}
