/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignNegativeKeyword } from './sponsored-products-campaign-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsCampaignNegativeKeywordsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsCampaignNegativeKeywordsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsCampaignNegativeKeywordsResponseContent
     */
    totalResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsCampaignNegativeKeywordsResponseContent
     */
    nextToken?: string;
    /**
     * 
     * @type {Array<SponsoredProductsCampaignNegativeKeyword>}
     * @memberof SponsoredProductsListSponsoredProductsCampaignNegativeKeywordsResponseContent
     */
    campaignNegativeKeywords?: Array<SponsoredProductsCampaignNegativeKeyword>;
}
