/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SponsoredProductsCreateDraftProductAd
 */
export interface SponsoredProductsCreateDraftProductAd {
    /**
     * The campaign identifier.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftProductAd
     */
    campaignId: string;
    /**
     * The custom text to use for creating a custom text ad for the associated ASIN. Defined only for KDP Authors and Book Vendors in US marketplace.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftProductAd
     */
    customText?: string;
    /**
     * The ASIN associated with the product. Defined for vendors only.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftProductAd
     */
    asin?: string;
    /**
     * The SKU associated with the product. Defined for seller accounts only.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftProductAd
     */
    sku?: string;
    /**
     * The ad group identifier.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftProductAd
     */
    adGroupId: string;
}
