/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityState } from './sponsored-products-entity-state';
import { SponsoredProductsExpressionType } from './sponsored-products-expression-type';
import { SponsoredProductsTargetingClauseExtendedData } from './sponsored-products-targeting-clause-extended-data';
import { SponsoredProductsTargetingExpressionPredicate } from './sponsored-products-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetingClause
 */
export interface SponsoredProductsTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsTargetingExpressionPredicate>}
     * @memberof SponsoredProductsTargetingClause
     */
    expression: Array<SponsoredProductsTargetingExpressionPredicate>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsTargetingClause
     */
    targetId: string;
    /**
     * The resolved targeting expression.
     * @type {Array<SponsoredProductsTargetingExpressionPredicate>}
     * @memberof SponsoredProductsTargetingClause
     */
    resolvedExpression: Array<SponsoredProductsTargetingExpressionPredicate>;
    /**
     * The identifier of the campaign to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsTargetingClause
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsExpressionType}
     * @memberof SponsoredProductsTargetingClause
     */
    expressionType: SponsoredProductsExpressionType;
    /**
     * 
     * @type {SponsoredProductsEntityState}
     * @memberof SponsoredProductsTargetingClause
     */
    state: SponsoredProductsEntityState;
    /**
     * The bid for ads sourced using the target. Targets that do not have bid values in listTargetingClauses will inherit the defaultBid from the adGroup level. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsTargetingClause
     */
    bid?: number;
    /**
     * The identifier of the ad group to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsTargetingClause
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsTargetingClauseExtendedData}
     * @memberof SponsoredProductsTargetingClause
     */
    extendedData?: SponsoredProductsTargetingClauseExtendedData;
}
