/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsTargetMutationErrorSelector } from './sponsored-products-target-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetMutationError
 */
export interface SponsoredProductsTargetMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsTargetMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsTargetMutationErrorSelector}
     * @memberof SponsoredProductsTargetMutationError
     */
    errorValue: SponsoredProductsTargetMutationErrorSelector;
}
