/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsProductAdAccessErrorSelector } from './sponsored-products-product-ad-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsProductAdAccessError
 */
export interface SponsoredProductsProductAdAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsProductAdAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsProductAdAccessErrorSelector}
     * @memberof SponsoredProductsProductAdAccessError
     */
    errorValue: SponsoredProductsProductAdAccessErrorSelector;
}
