/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateDraftCampaign } from './sponsored-products-create-draft-campaign';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsDraftCampaignsRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsDraftCampaignsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsCreateDraftCampaign>}
     * @memberof SponsoredProductsCreateSponsoredProductsDraftCampaignsRequestContent
     */
    campaigns: Array<SponsoredProductsCreateDraftCampaign>;
}
