/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsPlacement } from './sponsored-products-placement';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftCampaignPlacementBidding
 */
export interface SponsoredProductsDraftCampaignPlacementBidding {
    /**
     * 
     * @type {number}
     * @memberof SponsoredProductsDraftCampaignPlacementBidding
     */
    percentage?: number;
    /**
     * 
     * @type {SponsoredProductsPlacement}
     * @memberof SponsoredProductsDraftCampaignPlacementBidding
     */
    placement?: SponsoredProductsPlacement;
}
