/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateCampaignNegativeKeyword } from './sponsored-products-create-campaign-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsCampaignNegativeKeywordsRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsCampaignNegativeKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsCreateCampaignNegativeKeyword>}
     * @memberof SponsoredProductsCreateSponsoredProductsCampaignNegativeKeywordsRequestContent
     */
    campaignNegativeKeywords: Array<SponsoredProductsCreateCampaignNegativeKeyword>;
}
