/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateProductAd
 */
export interface SponsoredProductsUpdateProductAd {
    /**
     * The product ad identifier.
     * @type {string}
     * @memberof SponsoredProductsUpdateProductAd
     */
    adId: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsUpdateProductAd
     */
    state?: SponsoredProductsCreateOrUpdateEntityState;
}
