/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalProductIdentifiers } from './sponsored-products-global-product-identifiers';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateGlobalProductAd
 */
export interface SponsoredProductsUpdateGlobalProductAd {
    /**
     * The product ad identifier.
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalProductAd
     */
    adId: string;
    /**
     * Name for the product Ad
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalProductAd
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsGlobalProductIdentifiers}
     * @memberof SponsoredProductsUpdateGlobalProductAd
     */
    asin?: SponsoredProductsGlobalProductIdentifiers;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsUpdateGlobalProductAd
     */
    state?: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalProductIdentifiers}
     * @memberof SponsoredProductsUpdateGlobalProductAd
     */
    sku?: SponsoredProductsGlobalProductIdentifiers;
}
