/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalAdGroupExtendedData } from './sponsored-products-global-ad-group-extended-data';
import { SponsoredProductsGlobalBid } from './sponsored-products-global-bid';
import { SponsoredProductsGlobalEntityState } from './sponsored-products-global-entity-state';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalAdGroup
 */
export interface SponsoredProductsGlobalAdGroup {
    /**
     * The identifier of the campaign to which the keyword is associated.
     * @type {string}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    campaignId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    applicableMarketplaces?: Array<string>;
    /**
     * The name of the ad group.
     * @type {string}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    name: string;
    /**
     * 
     * @type {SponsoredProductsGlobalEntityState}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    state: SponsoredProductsGlobalEntityState;
    /**
     * The identifier of the keyword.
     * @type {string}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsGlobalBid}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    defaultBid: SponsoredProductsGlobalBid;
    /**
     * 
     * @type {SponsoredProductsGlobalAdGroupExtendedData}
     * @memberof SponsoredProductsGlobalAdGroup
     */
    extendedData?: SponsoredProductsGlobalAdGroupExtendedData;
}
