/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateAdGroup } from './sponsored-products-update-ad-group';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateAdGroup>}
     * @memberof SponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent
     */
    adGroups: Array<SponsoredProductsUpdateAdGroup>;
}
