/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateDynamicBidding } from './sponsored-products-create-or-update-dynamic-bidding';
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalBudget } from './sponsored-products-global-budget';
import { SponsoredProductsTags } from './sponsored-products-tags';
import { SponsoredProductsTargetingType } from './sponsored-products-targeting-type';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateGlobalCampaign
 */
export interface SponsoredProductsCreateGlobalCampaign {
    /**
     * The format of the date is YYYY-MM-DD.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    name: string;
    /**
     * 
     * @type {SponsoredProductsTargetingType}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    targetingType: SponsoredProductsTargetingType;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    state: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateDynamicBidding}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    dynamicBidding?: SponsoredProductsCreateOrUpdateDynamicBidding;
    /**
     * The format of the date is YYYY-MM-DD.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    startDate?: string;
    /**
     * 
     * @type {SponsoredProductsGlobalBudget}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    budget: SponsoredProductsGlobalBudget;
    /**
     * 
     * @type {SponsoredProductsTags}
     * @memberof SponsoredProductsCreateGlobalCampaign
     */
    tags?: SponsoredProductsTags;
}
