/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Match type for query filters. | Value |  Description | |-----------|------------| | `BROAD_MATCH` | Match if the queried value contains the filter value. (substring matching) | | `EXACT_MATCH` | Match if the queried value is exactly equivalent to the filter value. |
 * @export
 * @enum {string}
 */
export enum SponsoredProductsQueryTermMatchType {
    BROADMATCH = 'BROAD_MATCH',
    EXACTMATCH = 'EXACT_MATCH'
}

