/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The current resource state.
 * @export
 * @enum {string}
 */
export enum SponsoredProductsEntityState {
    ENABLED = 'ENABLED',
    PAUSED = 'PAUSED',
    ARCHIVED = 'ARCHIVED',
    ENABLING = 'ENABLING',
    USERDELETED = 'USER_DELETED',
    OTHER = 'OTHER'
}

