/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalNegativeKeywordText } from './sponsored-products-global-negative-keyword-text';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateGlobalCampaignNegativeKeyword
 */
export interface SponsoredProductsUpdateGlobalCampaignNegativeKeyword {
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalCampaignNegativeKeyword
     */
    keywordId: string;
    /**
     * Name for the keyword
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalCampaignNegativeKeyword
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsUpdateGlobalCampaignNegativeKeyword
     */
    state?: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalNegativeKeywordText}
     * @memberof SponsoredProductsUpdateGlobalCampaignNegativeKeyword
     */
    keywordText?: SponsoredProductsGlobalNegativeKeywordText;
}
