/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignNegativeTargetingClauseFailureResponseItem } from './sponsored-products-campaign-negative-targeting-clause-failure-response-item';
import { SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem } from './sponsored-products-campaign-negative-targeting-clause-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse
 */
export interface SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem>}
     * @memberof SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse
     */
    success?: Array<SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsCampaignNegativeTargetingClauseFailureResponseItem>}
     * @memberof SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse
     */
    error?: Array<SponsoredProductsCampaignNegativeTargetingClauseFailureResponseItem>;
}
