/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeywordFailureResponseItem } from './sponsored-products-keyword-failure-response-item';
import { SponsoredProductsKeywordSuccessResponseItem } from './sponsored-products-keyword-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkKeywordOperationResponse
 */
export interface SponsoredProductsBulkKeywordOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsKeywordSuccessResponseItem>}
     * @memberof SponsoredProductsBulkKeywordOperationResponse
     */
    success?: Array<SponsoredProductsKeywordSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsKeywordFailureResponseItem>}
     * @memberof SponsoredProductsBulkKeywordOperationResponse
     */
    error?: Array<SponsoredProductsKeywordFailureResponseItem>;
}
