/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalBid } from './sponsored-products-global-bid';
import { SponsoredProductsGlobalEntityState } from './sponsored-products-global-entity-state';
import { SponsoredProductsGlobalKeywordExtendedData } from './sponsored-products-global-keyword-extended-data';
import { SponsoredProductsGlobalKeywordText } from './sponsored-products-global-keyword-text';
import { SponsoredProductsMatchType } from './sponsored-products-match-type';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalKeyword
 */
export interface SponsoredProductsGlobalKeyword {
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsGlobalKeyword
     */
    keywordId: string;
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsGlobalKeyword
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsMatchType}
     * @memberof SponsoredProductsGlobalKeyword
     */
    matchType: SponsoredProductsMatchType;
    /**
     * Name for the Keyword
     * @type {string}
     * @memberof SponsoredProductsGlobalKeyword
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsGlobalEntityState}
     * @memberof SponsoredProductsGlobalKeyword
     */
    state: SponsoredProductsGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalBid}
     * @memberof SponsoredProductsGlobalKeyword
     */
    bid: SponsoredProductsGlobalBid;
    /**
     * entity object identifier
     * @type {string}
     * @memberof SponsoredProductsGlobalKeyword
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsGlobalKeywordText}
     * @memberof SponsoredProductsGlobalKeyword
     */
    keywordText: SponsoredProductsGlobalKeywordText;
    /**
     * 
     * @type {SponsoredProductsGlobalKeywordExtendedData}
     * @memberof SponsoredProductsGlobalKeyword
     */
    extendedData?: SponsoredProductsGlobalKeywordExtendedData;
}
