/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftAdGroup } from './sponsored-products-draft-ad-group';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsDraftAdGroupsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsDraftAdGroupsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsDraftAdGroupsResponseContent
     */
    totalResults?: number;
    /**
     * 
     * @type {Array<SponsoredProductsDraftAdGroup>}
     * @memberof SponsoredProductsListSponsoredProductsDraftAdGroupsResponseContent
     */
    adGroups?: Array<SponsoredProductsDraftAdGroup>;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsDraftAdGroupsResponseContent
     */
    nextToken?: string;
}
