/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsTargetingClauseSetupErrorReason {
    TARGETINGTYPENOTALLOWEDFORAUTOTARGETINGCAMPAIGN = 'TARGETING_TYPE_NOT_ALLOWED_FOR_AUTO_TARGETING_CAMPAIGN',
    TYPECONFLICTINADGROUP = 'TYPE_CONFLICT_IN_AD_GROUP',
    AUTOTARGETINGCLAUSECANNOTBECREATEDMANUALLY = 'AUTO_TARGETING_CLAUSE_CANNOT_BE_CREATED_MANUALLY',
    TARGETINGEXPRESSIONINVALIDVALUE = 'TARGETING_EXPRESSION_INVALID_VALUE'
}

