/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftNegativeTargetingClause } from './sponsored-products-draft-negative-targeting-clause';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
 */
export interface SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem {
    /**
     * the DraftNegativeTargetingClause ID
     * @type {string}
     * @memberof SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
     */
    targetId?: string;
    /**
     * the index of the DraftNegativeTargetingClause in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
     */
    index: number;
    /**
     * 
     * @type {SponsoredProductsDraftNegativeTargetingClause}
     * @memberof SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
     */
    negativeTargetingClause?: SponsoredProductsDraftNegativeTargetingClause;
}
