/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsTargetMutationError } from './sponsored-products-target-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetingClauseFailureResponseItem
 */
export interface SponsoredProductsTargetingClauseFailureResponseItem {
    /**
     * the index of the targetingClause in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsTargetingClauseFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsTargetMutationError>}
     * @memberof SponsoredProductsTargetingClauseFailureResponseItem
     */
    errors?: Array<SponsoredProductsTargetMutationError>;
}
