/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkCampaignNegativeKeywordOperationResponse } from './sponsored-products-bulk-campaign-negative-keyword-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkCampaignNegativeKeywordOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsResponseContent
     */
    campaignNegativeKeywords: SponsoredProductsBulkCampaignNegativeKeywordOperationResponse;
}
