/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityState } from './sponsored-products-entity-state';
import { SponsoredProductsExpressionTypeWithoutOther } from './sponsored-products-expression-type-without-other';
import { SponsoredProductsTargetingExpressionPredicateWithoutOther } from './sponsored-products-targeting-expression-predicate-without-other';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateDraftTargetingClause
 */
export interface SponsoredProductsCreateDraftTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsTargetingExpressionPredicateWithoutOther>}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    expression: Array<SponsoredProductsTargetingExpressionPredicateWithoutOther>;
    /**
     * The identifier of the campaign to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsExpressionTypeWithoutOther}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    expressionType: SponsoredProductsExpressionTypeWithoutOther;
    /**
     * 
     * @type {SponsoredProductsEntityState}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    state?: SponsoredProductsEntityState;
    /**
     * The bid for ads sourced using the target. Targets that do not have bid values in listDraftTargetingClauses will inherit the defaultBid from the adGroup level. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    bid?: number;
    /**
     * The identifier of the ad group to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateDraftTargetingClause
     */
    adGroupId: string;
}
