/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
/**
 * 
 * @export
 * @interface SponsoredProductsTargetCampaignAttributes
 */
export interface SponsoredProductsTargetCampaignAttributes {
    /**
     * The identifier of the target marketplace.
     * @type {string}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    marketplaceId: string;
    /**
     * The end date for the campaign in formats according to https://tools.ietf.org/html/rfc3339#section-5.6.
     * @type {string}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    endDate?: string;
    /**
     * The name to be appended to the campaign. If new name already exists, a number will be appended i.e. if \"Campaign Name Copy\" exist, we will name it \"Campaign Name Copy 1\"
     * @type {string}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    nameSuffix: string;
    /**
     * The start date of the campaign in formats according to https://tools.ietf.org/html/rfc3339#section-5.6.
     * @type {string}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    startDate?: string;
    /**
     * The advertiser id per the targeted marketplace. Advertiser id per marketplace can fetched through /v2/profiles API.
     * @type {string}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    advertiserId: string;
    /**
     * The budget for the campaign.
     * @type {number}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    budget?: number;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsTargetCampaignAttributes
     */
    status: SponsoredProductsCreateOrUpdateEntityState;
}
