/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateGlobalNegativeKeyword } from './sponsored-products-update-global-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsGlobalNegativeKeywordsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsGlobalNegativeKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateGlobalNegativeKeyword>}
     * @memberof SponsoredProductsUpdateSponsoredProductsGlobalNegativeKeywordsRequestContent
     */
    negativeKeywords: Array<SponsoredProductsUpdateGlobalNegativeKeyword>;
}
