/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalKeyword } from './sponsored-products-global-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsGlobalKeywordsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsGlobalKeywordsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsGlobalKeywordsResponseContent
     */
    totalResults?: number;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalKeyword>}
     * @memberof SponsoredProductsListSponsoredProductsGlobalKeywordsResponseContent
     */
    keywords?: Array<SponsoredProductsGlobalKeyword>;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsGlobalKeywordsResponseContent
     */
    nextToken?: string;
}
