/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsNegativeKeywordMutationError } from './sponsored-products-negative-keyword-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalNegativeKeywordFailureResponseItem
 */
export interface SponsoredProductsGlobalNegativeKeywordFailureResponseItem {
    /**
     * the index of the negativeKeyword in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsGlobalNegativeKeywordFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsNegativeKeywordMutationError>}
     * @memberof SponsoredProductsGlobalNegativeKeywordFailureResponseItem
     */
    errors?: Array<SponsoredProductsNegativeKeywordMutationError>;
}
