/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateDraftCampaignBudgetType } from './sponsored-products-create-or-update-draft-campaign-budget-type';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateOrUpdateDraftCampaignBudget
 */
export interface SponsoredProductsCreateOrUpdateDraftCampaignBudget {
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateDraftCampaignBudgetType}
     * @memberof SponsoredProductsCreateOrUpdateDraftCampaignBudget
     */
    budgetType: SponsoredProductsCreateOrUpdateDraftCampaignBudgetType;
    /**
     * Monetary value
     * @type {number}
     * @memberof SponsoredProductsCreateOrUpdateDraftCampaignBudget
     */
    budget: number;
}
