/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Structure describing error cause - location in the payload and data causing error
 * @export
 * @interface SponsoredProductsErrorCause
 */
export interface SponsoredProductsErrorCause {
    /**
     * Error location, JSON Path expression specifying element of API payload causing error
     * @type {string}
     * @memberof SponsoredProductsErrorCause
     */
    location: string;
    /**
     * optional value causing error
     * @type {string}
     * @memberof SponsoredProductsErrorCause
     */
    trigger?: string;
}
