/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalProductAdMarketplaceServingReason } from './sponsored-products-global-product-ad-marketplace-serving-reason';
import { SponsoredProductsGlobalProductAdMarketplaceServingStatus } from './sponsored-products-global-product-ad-marketplace-serving-status';
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsMarketplaceProductAdServingStatus
 */
export interface SponsoredProductsMarketplaceProductAdServingStatus {
    /**
     * 
     * @type {Array<SponsoredProductsGlobalProductAdMarketplaceServingReason>}
     * @memberof SponsoredProductsMarketplaceProductAdServingStatus
     */
    statusReasons?: Array<SponsoredProductsGlobalProductAdMarketplaceServingReason>;
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsMarketplaceProductAdServingStatus
     */
    marketplace?: SponsoredProductsMarketplace;
    /**
     * 
     * @type {SponsoredProductsGlobalProductAdMarketplaceServingStatus}
     * @memberof SponsoredProductsMarketplaceProductAdServingStatus
     */
    servingStatus: SponsoredProductsGlobalProductAdMarketplaceServingStatus;
}
