/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftNegativeKeywordMutationError } from './sponsored-products-draft-negative-keyword-mutation-error';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftNegativeKeywordFailureResponseItem
 */
export interface SponsoredProductsDraftNegativeKeywordFailureResponseItem {
    /**
     * the index of the draftNegativeKeyword in the array from the request body
     * @type {number}
     * @memberof SponsoredProductsDraftNegativeKeywordFailureResponseItem
     */
    index: number;
    /**
     * A list of validation errors
     * @type {Array<SponsoredProductsDraftNegativeKeywordMutationError>}
     * @memberof SponsoredProductsDraftNegativeKeywordFailureResponseItem
     */
    errors?: Array<SponsoredProductsDraftNegativeKeywordMutationError>;
}
