/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalTargetingClause } from './sponsored-products-global-targeting-clause';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsGlobalTargetingClausesResponseContent
 */
export interface SponsoredProductsListSponsoredProductsGlobalTargetingClausesResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsGlobalTargetingClausesResponseContent
     */
    totalResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsGlobalTargetingClausesResponseContent
     */
    nextToken?: string;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalTargetingClause>}
     * @memberof SponsoredProductsListSponsoredProductsGlobalTargetingClausesResponseContent
     */
    targetingClauses?: Array<SponsoredProductsGlobalTargetingClause>;
}
