/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalEntityServingStatus } from './sponsored-products-global-entity-serving-status';
import { SponsoredProductsGlobalKeywordServingStatusReason } from './sponsored-products-global-keyword-serving-status-reason';
import { SponsoredProductsMarketplaceLevelKeywordServingStatus } from './sponsored-products-marketplace-level-keyword-serving-status';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalKeywordServingStatus
 */
export interface SponsoredProductsGlobalKeywordServingStatus {
    /**
     * Serving status details of Keyword
     * @type {Array<SponsoredProductsGlobalKeywordServingStatusReason>}
     * @memberof SponsoredProductsGlobalKeywordServingStatus
     */
    statusReasons?: Array<SponsoredProductsGlobalKeywordServingStatusReason>;
    /**
     * The marketplace serving statuses.
     * @type {Array<SponsoredProductsMarketplaceLevelKeywordServingStatus>}
     * @memberof SponsoredProductsGlobalKeywordServingStatus
     */
    marketplaceKeywordServingStatus?: Array<SponsoredProductsMarketplaceLevelKeywordServingStatus>;
    /**
     * 
     * @type {SponsoredProductsGlobalEntityServingStatus}
     * @memberof SponsoredProductsGlobalKeywordServingStatus
     */
    keywordServingStatus?: SponsoredProductsGlobalEntityServingStatus;
}
