/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalCampaign } from './sponsored-products-global-campaign';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsGlobalCampaignsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsGlobalCampaignsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignsResponseContent
     */
    totalResults?: number;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaign>}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignsResponseContent
     */
    campaigns?: Array<SponsoredProductsGlobalCampaign>;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignsResponseContent
     */
    nextToken?: string;
}
