/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalTargetingExpressionPredicate } from './sponsored-products-global-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateGlobalNegativeTargetingClause
 */
export interface SponsoredProductsUpdateGlobalNegativeTargetingClause {
    /**
     * The NegativeTargeting expression.
     * @type {Array<SponsoredProductsGlobalTargetingExpressionPredicate>}
     * @memberof SponsoredProductsUpdateGlobalNegativeTargetingClause
     */
    expression?: Array<SponsoredProductsGlobalTargetingExpressionPredicate>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalNegativeTargetingClause
     */
    targetId: string;
    /**
     * Name for the negative targeting clause
     * @type {string}
     * @memberof SponsoredProductsUpdateGlobalNegativeTargetingClause
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsUpdateGlobalNegativeTargetingClause
     */
    state?: SponsoredProductsCreateOrUpdateGlobalEntityState;
}
