/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftCampaignMutationFailureResponseItem } from './sponsored-products-draft-campaign-mutation-failure-response-item';
import { SponsoredProductsDraftCampaignMutationSuccessResponseItem } from './sponsored-products-draft-campaign-mutation-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkDraftCampaignOperationResponse
 */
export interface SponsoredProductsBulkDraftCampaignOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsDraftCampaignMutationSuccessResponseItem>}
     * @memberof SponsoredProductsBulkDraftCampaignOperationResponse
     */
    success?: Array<SponsoredProductsDraftCampaignMutationSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsDraftCampaignMutationFailureResponseItem>}
     * @memberof SponsoredProductsBulkDraftCampaignOperationResponse
     */
    error?: Array<SponsoredProductsDraftCampaignMutationFailureResponseItem>;
}
