/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeywordServingStatus } from './sponsored-products-keyword-serving-status';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftKeywordExtendedData
 */
export interface SponsoredProductsDraftKeywordExtendedData {
    /**
     * Last updated date in ISO 8601.
     * @type {Date}
     * @memberof SponsoredProductsDraftKeywordExtendedData
     */
    lastUpdateDateTime?: Date;
    /**
     * 
     * @type {SponsoredProductsKeywordServingStatus}
     * @memberof SponsoredProductsDraftKeywordExtendedData
     */
    servingStatus?: SponsoredProductsKeywordServingStatus;
    /**
     * Creation date in ISO 8601.
     * @type {Date}
     * @memberof SponsoredProductsDraftKeywordExtendedData
     */
    creationDateTime?: Date;
}
