/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCopyCampaign } from './sponsored-products-copy-campaign';
import { SponsoredProductsCopyCampaignErrorDetail } from './sponsored-products-copy-campaign-error-detail';
/**
 * 
 * @export
 * @interface SponsoredProductsCopyCampaignResponse
 */
export interface SponsoredProductsCopyCampaignResponse {
    /**
     * Id of the request to be passed in GET /copy/{requestId}.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignResponse
     */
    requestId?: string;
    /**
     * 
     * @type {SponsoredProductsCopyCampaignErrorDetail}
     * @memberof SponsoredProductsCopyCampaignResponse
     */
    errorDetail?: SponsoredProductsCopyCampaignErrorDetail;
    /**
     * 
     * @type {SponsoredProductsCopyCampaign}
     * @memberof SponsoredProductsCopyCampaignResponse
     */
    copyCampaignItem?: SponsoredProductsCopyCampaign;
}
