/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalAdGroup } from './sponsored-products-global-ad-group';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsGlobalAdGroupsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsGlobalAdGroupsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsGlobalAdGroupsResponseContent
     */
    totalResults?: number;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalAdGroup>}
     * @memberof SponsoredProductsListSponsoredProductsGlobalAdGroupsResponseContent
     */
    adGroups?: Array<SponsoredProductsGlobalAdGroup>;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsGlobalAdGroupsResponseContent
     */
    nextToken?: string;
}
