/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateDraftAdGroup } from './sponsored-products-create-draft-ad-group';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsCreateDraftAdGroup>}
     * @memberof SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
     */
    adGroups: Array<SponsoredProductsCreateDraftAdGroup>;
}
