/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateKeyword } from './sponsored-products-update-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsKeywordsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateKeyword>}
     * @memberof SponsoredProductsUpdateSponsoredProductsKeywordsRequestContent
     */
    keywords: Array<SponsoredProductsUpdateKeyword>;
}
