/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBillingErrorReason } from './sponsored-products-billing-error-reason';
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
/**
 * Errors related to bids
 * @export
 * @interface SponsoredProductsBillingError
 */
export interface SponsoredProductsBillingError {
    /**
     * 
     * @type {SponsoredProductsBillingErrorReason}
     * @memberof SponsoredProductsBillingError
     */
    reason: SponsoredProductsBillingErrorReason;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsBillingError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsBillingError
     */
    message: string;
}
