/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateEntityState } from './sponsored-products-create-or-update-entity-state';
import { SponsoredProductsExpressionTypeWithoutOther } from './sponsored-products-expression-type-without-other';
import { SponsoredProductsTargetingExpressionPredicateWithoutOther } from './sponsored-products-targeting-expression-predicate-without-other';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateTargetingClause
 */
export interface SponsoredProductsUpdateTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsTargetingExpressionPredicateWithoutOther>}
     * @memberof SponsoredProductsUpdateTargetingClause
     */
    expression?: Array<SponsoredProductsTargetingExpressionPredicateWithoutOther>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsUpdateTargetingClause
     */
    targetId: string;
    /**
     * 
     * @type {SponsoredProductsExpressionTypeWithoutOther}
     * @memberof SponsoredProductsUpdateTargetingClause
     */
    expressionType?: SponsoredProductsExpressionTypeWithoutOther;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateEntityState}
     * @memberof SponsoredProductsUpdateTargetingClause
     */
    state?: SponsoredProductsCreateOrUpdateEntityState;
    /**
     * The bid for ads sourced using the target. Targets that do not have bid values in listTargetingClauses will inherit the defaultBid from the adGroup level. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
     * @type {number}
     * @memberof SponsoredProductsUpdateTargetingClause
     */
    bid?: number | null;
}
