/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUnsupportedMediaTypeErrorCode } from './sponsored-products-unsupported-media-type-error-code';
/**
 * 
 * @export
 * @interface SponsoredProductsUnsupportedMediaTypeExceptionResponseContent
 */
export interface SponsoredProductsUnsupportedMediaTypeExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsUnsupportedMediaTypeErrorCode}
     * @memberof SponsoredProductsUnsupportedMediaTypeExceptionResponseContent
     */
    code: SponsoredProductsUnsupportedMediaTypeErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsUnsupportedMediaTypeExceptionResponseContent
     */
    message: string;
}
