/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalTargetingClauseServingStatus } from './sponsored-products-global-targeting-clause-serving-status';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalNegativeTargetingClauseExtendedData
 */
export interface SponsoredProductsGlobalNegativeTargetingClauseExtendedData {
    /**
     * 
     * @type {SponsoredProductsGlobalTargetingClauseServingStatus}
     * @memberof SponsoredProductsGlobalNegativeTargetingClauseExtendedData
     */
    servingStatus?: SponsoredProductsGlobalTargetingClauseServingStatus;
}
