/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkNegativeTargetingClauseOperationResponse } from './sponsored-products-bulk-negative-targeting-clause-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsNegativeTargetingClausesResponseContent
 */
export interface SponsoredProductsUpdateSponsoredProductsNegativeTargetingClausesResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkNegativeTargetingClauseOperationResponse}
     * @memberof SponsoredProductsUpdateSponsoredProductsNegativeTargetingClausesResponseContent
     */
    negativeTargetingClauses: SponsoredProductsBulkNegativeTargetingClauseOperationResponse;
}
