/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCampaignAccessErrorSelector } from './sponsored-products-campaign-access-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsCampaignAccessError
 */
export interface SponsoredProductsCampaignAccessError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsCampaignAccessError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsCampaignAccessErrorSelector}
     * @memberof SponsoredProductsCampaignAccessError
     */
    errorValue: SponsoredProductsCampaignAccessErrorSelector;
}
