/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateGlobalNegativeKeyword } from './sponsored-products-create-global-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsRequestContent {
    /**
     * An array of negativeKeywords.
     * @type {Array<SponsoredProductsCreateGlobalNegativeKeyword>}
     * @memberof SponsoredProductsCreateSponsoredProductsGlobalNegativeKeywordsRequestContent
     */
    negativeKeywords?: Array<SponsoredProductsCreateGlobalNegativeKeyword>;
}
