/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsProductAd } from './sponsored-products-product-ad';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsProductAdsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsProductAdsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsProductAdsResponseContent
     */
    totalResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsProductAdsResponseContent
     */
    nextToken?: string;
    /**
     * 
     * @type {Array<SponsoredProductsProductAd>}
     * @memberof SponsoredProductsListSponsoredProductsProductAdsResponseContent
     */
    productAds?: Array<SponsoredProductsProductAd>;
}
