/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkGlobalProductAdOperationResponse } from './sponsored-products-bulk-global-product-ad-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsGlobalProductAdsResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsGlobalProductAdsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkGlobalProductAdOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsGlobalProductAdsResponseContent
     */
    productAds: SponsoredProductsBulkGlobalProductAdOperationResponse;
}
