/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsAsyncStatus } from './sponsored-products-async-status';
import { SponsoredProductsCopyCampaignErrorDetail } from './sponsored-products-copy-campaign-error-detail';
/**
 * 
 * @export
 * @interface SponsoredProductsCopyCampaignTaskDetails
 */
export interface SponsoredProductsCopyCampaignTaskDetails {
    /**
     * The target marketplace in obfuscated format.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    targetMarketplaceId?: string;
    /**
     * The identifier of the campaign in the target marketplace.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    targetCampaignId?: string;
    /**
     * Percent of copy operation that is complete
     * @type {number}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    percentageCompleted?: number;
    /**
     * The source marketplace in obfuscated format.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    sourceMarketplaceId?: string;
    /**
     * The identifier of the campaign in the source marketplace.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    sourceCampaignId?: string;
    /**
     * The identifier of the advertiser in source marketplace.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    sourceAdvertiserId?: string;
    /**
     * The identifier of the advertiser in the target marketplace.
     * @type {string}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    targetAdvertiserId?: string;
    /**
     * 
     * @type {SponsoredProductsAsyncStatus}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    status?: SponsoredProductsAsyncStatus;
    /**
     * Errors that could occur during async process (up to 10)
     * @type {Array<SponsoredProductsCopyCampaignErrorDetail>}
     * @memberof SponsoredProductsCopyCampaignTaskDetails
     */
    errorDetails?: Array<SponsoredProductsCopyCampaignErrorDetail>;
}
