/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalBid } from './sponsored-products-global-bid';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateGlobalAdGroup
 */
export interface SponsoredProductsCreateGlobalAdGroup {
    /**
     * The identifier of the campaign to which the AdGroup is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalAdGroup
     */
    campaignId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SponsoredProductsCreateGlobalAdGroup
     */
    applicableMarketplaces?: Array<string>;
    /**
     * The name of the ad group.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalAdGroup
     */
    name: string;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsCreateGlobalAdGroup
     */
    state: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalBid}
     * @memberof SponsoredProductsCreateGlobalAdGroup
     */
    defaultBid: SponsoredProductsGlobalBid;
}
