/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsCurrency {
    USD = 'USD',
    EUR = 'EUR',
    GBP = 'GBP',
    MXN = 'MXN',
    JPY = 'JPY',
    INR = 'INR',
    PLN = 'PLN',
    SGD = 'SGD',
    AUD = 'AUD',
    CAD = 'CAD',
    BRL = 'BRL',
    SEK = 'SEK',
    TRY = 'TRY',
    AED = 'AED',
    SAR = 'SAR',
    EGP = 'EGP'
}

