/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsProductAd } from './sponsored-products-product-ad';
/**
 * 
 * @export
 * @interface SponsoredProductsProductAdSuccessResponseItem
 */
export interface SponsoredProductsProductAdSuccessResponseItem {
    /**
     * the ProductAd ID
     * @type {string}
     * @memberof SponsoredProductsProductAdSuccessResponseItem
     */
    adId?: string;
    /**
     * The index in the original list from the request.
     * @type {number}
     * @memberof SponsoredProductsProductAdSuccessResponseItem
     */
    index: number;
    /**
     * 
     * @type {SponsoredProductsProductAd}
     * @memberof SponsoredProductsProductAdSuccessResponseItem
     */
    productAd?: SponsoredProductsProductAd;
}
