/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateGlobalNegativeTargetingClause } from './sponsored-products-create-global-negative-targeting-clause';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsGlobalNegativeTargetingClausesRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsGlobalNegativeTargetingClausesRequestContent {
    /**
     * An array of negativeTargeting.
     * @type {Array<SponsoredProductsCreateGlobalNegativeTargetingClause>}
     * @memberof SponsoredProductsCreateSponsoredProductsGlobalNegativeTargetingClausesRequestContent
     */
    negativeTargetingClauses?: Array<SponsoredProductsCreateGlobalNegativeTargetingClause>;
}
