/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateDraftNegativeTargetingClause } from './sponsored-products-create-draft-negative-targeting-clause';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsDraftNegativeTargetingClausesRequestContent
 */
export interface SponsoredProductsCreateSponsoredProductsDraftNegativeTargetingClausesRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsCreateDraftNegativeTargetingClause>}
     * @memberof SponsoredProductsCreateSponsoredProductsDraftNegativeTargetingClausesRequestContent
     */
    negativeTargetingClauses: Array<SponsoredProductsCreateDraftNegativeTargetingClause>;
}
