/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkGlobalCampaignOperationResponse } from './sponsored-products-bulk-global-campaign-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsGlobalCampaignsResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsGlobalCampaignsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkGlobalCampaignOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsGlobalCampaignsResponseContent
     */
    campaigns: SponsoredProductsBulkGlobalCampaignOperationResponse;
}
