/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDuplicateValueErrorReason } from './sponsored-products-duplicate-value-error-reason';
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsDuplicateValueError
 */
export interface SponsoredProductsDuplicateValueError {
    /**
     * 
     * @type {SponsoredProductsDuplicateValueErrorReason}
     * @memberof SponsoredProductsDuplicateValueError
     */
    reason: SponsoredProductsDuplicateValueErrorReason;
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsDuplicateValueError
     */
    marketplace?: SponsoredProductsMarketplace;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsDuplicateValueError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsDuplicateValueError
     */
    message: string;
}
