/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsProductAdMutationErrorSelector } from './sponsored-products-product-ad-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsProductAdMutationError
 */
export interface SponsoredProductsProductAdMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsProductAdMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsProductAdMutationErrorSelector}
     * @memberof SponsoredProductsProductAdMutationError
     */
    errorValue: SponsoredProductsProductAdMutationErrorSelector;
}
