/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalCampaignNegativeKeywordFailureResponseItem } from './sponsored-products-global-campaign-negative-keyword-failure-response-item';
import { SponsoredProductsGlobalCampaignNegativeKeywordSuccessResponseItem } from './sponsored-products-global-campaign-negative-keyword-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkGlobalCampaignNegativeKeywordOperationResponse
 */
export interface SponsoredProductsBulkGlobalCampaignNegativeKeywordOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaignNegativeKeywordSuccessResponseItem>}
     * @memberof SponsoredProductsBulkGlobalCampaignNegativeKeywordOperationResponse
     */
    success?: Array<SponsoredProductsGlobalCampaignNegativeKeywordSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaignNegativeKeywordFailureResponseItem>}
     * @memberof SponsoredProductsBulkGlobalCampaignNegativeKeywordOperationResponse
     */
    error?: Array<SponsoredProductsGlobalCampaignNegativeKeywordFailureResponseItem>;
}
