/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkDraftCampaignOperationResponse } from './sponsored-products-bulk-draft-campaign-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsPromoteSponsoredProductsDraftCampaignsResponseContent
 */
export interface SponsoredProductsPromoteSponsoredProductsDraftCampaignsResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkDraftCampaignOperationResponse}
     * @memberof SponsoredProductsPromoteSponsoredProductsDraftCampaignsResponseContent
     */
    campaigns: SponsoredProductsBulkDraftCampaignOperationResponse;
}
