/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SponsoredProductsMalformedValueErrorReason {
    FORBIDDENCHARS = 'FORBIDDEN_CHARS',
    PATTERNNOTMATCHED = 'PATTERN_NOT_MATCHED',
    TOOLONG = 'TOO_LONG',
    TOOSHORT = 'TOO_SHORT',
    LEADINGORTRAILINGWHITESPACE = 'LEADING_OR_TRAILING_WHITESPACE',
    BLANK = 'BLANK'
}

