/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityState } from './sponsored-products-entity-state';
import { SponsoredProductsNegativeTargetingClauseExtendedData } from './sponsored-products-negative-targeting-clause-extended-data';
import { SponsoredProductsNegativeTargetingExpressionPredicate } from './sponsored-products-negative-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsNegativeTargetingClause
 */
export interface SponsoredProductsNegativeTargetingClause {
    /**
     * The NegativeTargeting expression.
     * @type {Array<SponsoredProductsNegativeTargetingExpressionPredicate>}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    expression: Array<SponsoredProductsNegativeTargetingExpressionPredicate>;
    /**
     * The target identifier
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    targetId: string;
    /**
     * The resolved NegativeTargeting expression.
     * @type {Array<SponsoredProductsNegativeTargetingExpressionPredicate>}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    resolvedExpression: Array<SponsoredProductsNegativeTargetingExpressionPredicate>;
    /**
     * The identifier of the campaign to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    campaignId: string;
    /**
     * 
     * @type {SponsoredProductsEntityState}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    state: SponsoredProductsEntityState;
    /**
     * The identifier of the ad group to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    adGroupId: string;
    /**
     * 
     * @type {SponsoredProductsNegativeTargetingClauseExtendedData}
     * @memberof SponsoredProductsNegativeTargetingClause
     */
    extendedData?: SponsoredProductsNegativeTargetingClauseExtendedData;
}
