/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalProductAdServingStatus } from './sponsored-products-global-product-ad-serving-status';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalProductAdExtendedData
 */
export interface SponsoredProductsGlobalProductAdExtendedData {
    /**
     * 
     * @type {SponsoredProductsGlobalProductAdServingStatus}
     * @memberof SponsoredProductsGlobalProductAdExtendedData
     */
    servingStatus?: SponsoredProductsGlobalProductAdServingStatus;
}
