/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftTargetingClauseFailureResponseItem } from './sponsored-products-draft-targeting-clause-failure-response-item';
import { SponsoredProductsDraftTargetingClauseSuccessResponseItem } from './sponsored-products-draft-targeting-clause-success-response-item';
/**
 * 
 * @export
 * @interface SponsoredProductsBulkDraftTargetingClauseOperationResponse
 */
export interface SponsoredProductsBulkDraftTargetingClauseOperationResponse {
    /**
     * 
     * @type {Array<SponsoredProductsDraftTargetingClauseSuccessResponseItem>}
     * @memberof SponsoredProductsBulkDraftTargetingClauseOperationResponse
     */
    success?: Array<SponsoredProductsDraftTargetingClauseSuccessResponseItem>;
    /**
     * 
     * @type {Array<SponsoredProductsDraftTargetingClauseFailureResponseItem>}
     * @memberof SponsoredProductsBulkDraftTargetingClauseOperationResponse
     */
    error?: Array<SponsoredProductsDraftTargetingClauseFailureResponseItem>;
}
