/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityState } from './sponsored-products-entity-state';
import { SponsoredProductsMarketplaceState } from './sponsored-products-marketplace-state';
/**
 * 
 * @export
 * @interface SponsoredProductsGlobalEntityState
 */
export interface SponsoredProductsGlobalEntityState {
    /**
     * 
     * @type {Array<SponsoredProductsMarketplaceState>}
     * @memberof SponsoredProductsGlobalEntityState
     */
    marketplaceSettings?: Array<SponsoredProductsMarketplaceState>;
    /**
     * 
     * @type {SponsoredProductsEntityState}
     * @memberof SponsoredProductsGlobalEntityState
     */
    state: SponsoredProductsEntityState;
}
