/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsEntityStateFilter } from './sponsored-products-entity-state-filter';
import { SponsoredProductsKeywordTextFilter } from './sponsored-products-keyword-text-filter';
import { SponsoredProductsMatchType } from './sponsored-products-match-type';
import { SponsoredProductsObjectIdFilter } from './sponsored-products-object-id-filter';
import { SponsoredProductsReducedObjectIdFilter } from './sponsored-products-reduced-object-id-filter';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsKeywordsRequestContent
 */
export interface SponsoredProductsListSponsoredProductsKeywordsRequestContent {
    /**
     * 
     * @type {SponsoredProductsReducedObjectIdFilter}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    campaignIdFilter?: SponsoredProductsReducedObjectIdFilter;
    /**
     * 
     * @type {SponsoredProductsEntityStateFilter}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    stateFilter?: SponsoredProductsEntityStateFilter;
    /**
     * Number of records to include in the paginated response. Defaults to max page size for given API
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    maxResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    nextToken?: string;
    /**
     * 
     * @type {SponsoredProductsReducedObjectIdFilter}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    adGroupIdFilter?: SponsoredProductsReducedObjectIdFilter;
    /**
     * Whether to get entity with extended data fields such as creationDate, lastUpdateDate, servingStatus
     * @type {boolean}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    includeExtendedDataFields?: boolean;
    /**
     * Restricts results to keywords associated with locale
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    locale?: string;
    /**
     * 
     * @type {SponsoredProductsKeywordTextFilter}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    keywordTextFilter?: SponsoredProductsKeywordTextFilter;
    /**
     * 
     * @type {SponsoredProductsObjectIdFilter}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    keywordIdFilter?: SponsoredProductsObjectIdFilter;
    /**
     * Only the keyword with match type that is in this list will be listed
     * @type {Array<SponsoredProductsMatchType>}
     * @memberof SponsoredProductsListSponsoredProductsKeywordsRequestContent
     */
    matchTypeFilter?: Array<SponsoredProductsMatchType>;
}
