/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsKeywordMutationErrorSelector } from './sponsored-products-keyword-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsKeywordMutationError
 */
export interface SponsoredProductsKeywordMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsKeywordMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsKeywordMutationErrorSelector}
     * @memberof SponsoredProductsKeywordMutationError
     */
    errorValue: SponsoredProductsKeywordMutationErrorSelector;
}
