/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalCampaignNegativeKeyword } from './sponsored-products-global-campaign-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsListSponsoredProductsGlobalCampaignNegativeKeywordsResponseContent
 */
export interface SponsoredProductsListSponsoredProductsGlobalCampaignNegativeKeywordsResponseContent {
    /**
     * The total number of entities
     * @type {number}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignNegativeKeywordsResponseContent
     */
    totalResults?: number;
    /**
     * token value allowing to navigate to the next response page
     * @type {string}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignNegativeKeywordsResponseContent
     */
    nextToken?: string;
    /**
     * 
     * @type {Array<SponsoredProductsGlobalCampaignNegativeKeyword>}
     * @memberof SponsoredProductsListSponsoredProductsGlobalCampaignNegativeKeywordsResponseContent
     */
    campaignNegativeKeywords?: Array<SponsoredProductsGlobalCampaignNegativeKeyword>;
}
