/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsInvalidArgumentErrorCode } from './sponsored-products-invalid-argument-error-code';
import { SponsoredProductsNegativeTargetAccessError } from './sponsored-products-negative-target-access-error';
/**
 * Exception resulting in accessing campaign management entities
 * @export
 * @interface SponsoredProductsNegativeTargetAccessExceptionResponseContent
 */
export interface SponsoredProductsNegativeTargetAccessExceptionResponseContent {
    /**
     * 
     * @type {SponsoredProductsInvalidArgumentErrorCode}
     * @memberof SponsoredProductsNegativeTargetAccessExceptionResponseContent
     */
    code: SponsoredProductsInvalidArgumentErrorCode;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsNegativeTargetAccessExceptionResponseContent
     */
    message: string;
    /**
     * 
     * @type {Array<SponsoredProductsNegativeTargetAccessError>}
     * @memberof SponsoredProductsNegativeTargetAccessExceptionResponseContent
     */
    errors?: Array<SponsoredProductsNegativeTargetAccessError>;
}
