/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsCreateExpressionType } from './sponsored-products-create-expression-type';
import { SponsoredProductsCreateOrUpdateGlobalEntityState } from './sponsored-products-create-or-update-global-entity-state';
import { SponsoredProductsGlobalBid } from './sponsored-products-global-bid';
import { SponsoredProductsGlobalTargetingExpressionPredicate } from './sponsored-products-global-targeting-expression-predicate';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateGlobalTargetingClause
 */
export interface SponsoredProductsCreateGlobalTargetingClause {
    /**
     * The targeting expression.
     * @type {Array<SponsoredProductsGlobalTargetingExpressionPredicate>}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    expression: Array<SponsoredProductsGlobalTargetingExpressionPredicate>;
    /**
     * The identifier of the campaign to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    campaignId: string;
    /**
     * Name for the targeting clause
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    name?: string;
    /**
     * 
     * @type {SponsoredProductsCreateExpressionType}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    expressionType: SponsoredProductsCreateExpressionType;
    /**
     * 
     * @type {SponsoredProductsCreateOrUpdateGlobalEntityState}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    state: SponsoredProductsCreateOrUpdateGlobalEntityState;
    /**
     * 
     * @type {SponsoredProductsGlobalBid}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    bid?: SponsoredProductsGlobalBid;
    /**
     * The identifier of the ad group to which this target is associated.
     * @type {string}
     * @memberof SponsoredProductsCreateGlobalTargetingClause
     */
    adGroupId: string;
}
