/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateDraftCampaign } from './sponsored-products-update-draft-campaign';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsDraftCampaignsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsDraftCampaignsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateDraftCampaign>}
     * @memberof SponsoredProductsUpdateSponsoredProductsDraftCampaignsRequestContent
     */
    campaigns: Array<SponsoredProductsUpdateDraftCampaign>;
}
