/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsDraftAdGroupMutationErrorSelector } from './sponsored-products-draft-ad-group-mutation-error-selector';
/**
 * 
 * @export
 * @interface SponsoredProductsDraftAdGroupMutationError
 */
export interface SponsoredProductsDraftAdGroupMutationError {
    /**
     * The type of the error
     * @type {string}
     * @memberof SponsoredProductsDraftAdGroupMutationError
     */
    errorType: string;
    /**
     * 
     * @type {SponsoredProductsDraftAdGroupMutationErrorSelector}
     * @memberof SponsoredProductsDraftAdGroupMutationError
     */
    errorValue: SponsoredProductsDraftAdGroupMutationErrorSelector;
}
