/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkDraftNegativeTargetingClauseOperationResponse } from './sponsored-products-bulk-draft-negative-targeting-clause-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
 */
export interface SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkDraftNegativeTargetingClauseOperationResponse}
     * @memberof SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
     */
    negativeTargetingClauses: SponsoredProductsBulkDraftNegativeTargetingClauseOperationResponse;
}
