/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse } from './sponsored-products-bulk-campaign-negative-targeting-clause-operation-response';
/**
 * 
 * @export
 * @interface SponsoredProductsCreateSponsoredProductsCampaignNegativeTargetingClausesResponseContent
 */
export interface SponsoredProductsCreateSponsoredProductsCampaignNegativeTargetingClausesResponseContent {
    /**
     * 
     * @type {SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse}
     * @memberof SponsoredProductsCreateSponsoredProductsCampaignNegativeTargetingClausesResponseContent
     */
    campaignNegativeTargetingClauses: SponsoredProductsBulkCampaignNegativeTargetingClauseOperationResponse;
}
