/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsErrorCause } from './sponsored-products-error-cause';
import { SponsoredProductsInternalServerErrorReason } from './sponsored-products-internal-server-error-reason';
/**
 * Error that represents non-retryable API service error. Sending the same request will result in another error.
 * @export
 * @interface SponsoredProductsInternalServerError
 */
export interface SponsoredProductsInternalServerError {
    /**
     * 
     * @type {SponsoredProductsInternalServerErrorReason}
     * @memberof SponsoredProductsInternalServerError
     */
    reason: SponsoredProductsInternalServerErrorReason;
    /**
     * 
     * @type {SponsoredProductsErrorCause}
     * @memberof SponsoredProductsInternalServerError
     */
    cause?: SponsoredProductsErrorCause;
    /**
     * Human readable error message
     * @type {string}
     * @memberof SponsoredProductsInternalServerError
     */
    message: string;
}
