/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsUpdateGlobalCampaignNegativeKeyword } from './sponsored-products-update-global-campaign-negative-keyword';
/**
 * 
 * @export
 * @interface SponsoredProductsUpdateSponsoredProductsGlobalCampaignNegativeKeywordsRequestContent
 */
export interface SponsoredProductsUpdateSponsoredProductsGlobalCampaignNegativeKeywordsRequestContent {
    /**
     * 
     * @type {Array<SponsoredProductsUpdateGlobalCampaignNegativeKeyword>}
     * @memberof SponsoredProductsUpdateSponsoredProductsGlobalCampaignNegativeKeywordsRequestContent
     */
    campaignNegativeKeywords: Array<SponsoredProductsUpdateGlobalCampaignNegativeKeyword>;
}
