/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SponsoredProductsGlobalKeywordMarketplaceServingStatus } from './sponsored-products-global-keyword-marketplace-serving-status';
import { SponsoredProductsGlobalKeywordMarketplaceServingStatusReason } from './sponsored-products-global-keyword-marketplace-serving-status-reason';
import { SponsoredProductsMarketplace } from './sponsored-products-marketplace';
/**
 * 
 * @export
 * @interface SponsoredProductsMarketplaceTargetingClauseServingStatus
 */
export interface SponsoredProductsMarketplaceTargetingClauseServingStatus {
    /**
     * 
     * @type {Array<SponsoredProductsGlobalKeywordMarketplaceServingStatusReason>}
     * @memberof SponsoredProductsMarketplaceTargetingClauseServingStatus
     */
    statusReasons?: Array<SponsoredProductsGlobalKeywordMarketplaceServingStatusReason>;
    /**
     * 
     * @type {SponsoredProductsMarketplace}
     * @memberof SponsoredProductsMarketplaceTargetingClauseServingStatus
     */
    marketplace?: SponsoredProductsMarketplace;
    /**
     * 
     * @type {SponsoredProductsGlobalKeywordMarketplaceServingStatus}
     * @memberof SponsoredProductsMarketplaceTargetingClauseServingStatus
     */
    servingStatus: SponsoredProductsGlobalKeywordMarketplaceServingStatus;
}
