/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The budget rule state.
 * @export
 * @enum {string}
 */
export enum State {
    ACTIVE = 'ACTIVE',
    PAUSED = 'PAUSED'
}

