/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Contains suggested recommendation for the auto targeting group.
 * @export
 * @interface TargetingGroupBidRecommendation
 */
export interface TargetingGroupBidRecommendation {
    /**
     * The suggested bid value associated with this targeting.
     * @type {number}
     * @memberof TargetingGroupBidRecommendation
     */
    suggestedBid?: number;
    /**
     * The target identifier.
     * @type {string}
     * @memberof TargetingGroupBidRecommendation
     */
    targetId?: string;
    /**
     * The type of targeting group expression. | Value | Description | | --- | --- | | `LOOSE_MATCH` | This will show your ad to shoppers who use search terms loosely related to your products.| | `CLOSE_MATCH` | This will show your ad to shoppers who use search terms closely related to your products.| | `COMPLEMENTS` | This will show your ad to shoppers who view the detail pages of products that complement your product.| | `SUBSTITUTES` | This will show your ad to shoppers who use detail pages of products similar to yours.|
     * @type {string}
     * @memberof TargetingGroupBidRecommendation
     */
    targetingGroupExpression?: TargetingGroupBidRecommendationTargetingGroupExpressionEnum;
    /**
     * Type of suggested action.
     * @type {string}
     * @memberof TargetingGroupBidRecommendation
     */
    action?: TargetingGroupBidRecommendationActionEnum;
    /**
     * The ad group identifier.
     * @type {string}
     * @memberof TargetingGroupBidRecommendation
     */
    adGroupId?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum TargetingGroupBidRecommendationTargetingGroupExpressionEnum {
    CLOSEMATCH = 'CLOSE_MATCH',
    LOOSEMATCH = 'LOOSE_MATCH',
    SUBSTITUTES = 'SUBSTITUTES',
    COMPLEMENTS = 'COMPLEMENTS'
}
/**
    * @export
    * @enum {string}
    */
export enum TargetingGroupBidRecommendationActionEnum {
    ADD = 'ADD',
    REMOVE = 'REMOVE',
    INCREASE = 'INCREASE',
    DECREASE = 'DECREASE'
}

