/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The targeting expression. The `type` property specifies the targeting option. Use `CLOSE_MATCH` to match your auto targeting ads closely to the specified value. Use `LOOSE_MATCH` to match your auto targeting ads broadly to the specified value. Use `SUBSTITUTES` to display your auto targeting ads along with substitutable products. Use `COMPLEMENTS` to display your auto targeting ads along with affiliated products. Use `KEYWORD_BROAD_MATCH` to broadly match your keyword targeting ads with search queries. Use `KEYWORD_EXACT_MATCH` to exactly match your keyword targeting ads with search queries. Use `KEYWORD_PHRASE_MATCH` to match your keyword targeting ads with search phrases.
 * @export
 * @interface TargetingExpression
 */
export interface TargetingExpression {
    /**
     * 
     * @type {string}
     * @memberof TargetingExpression
     */
    type: TargetingExpressionTypeEnum;
    /**
     * The targeting expression value.
     * @type {string}
     * @memberof TargetingExpression
     */
    value?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum TargetingExpressionTypeEnum {
    CLOSEMATCH = 'CLOSE_MATCH',
    LOOSEMATCH = 'LOOSE_MATCH',
    SUBSTITUTES = 'SUBSTITUTES',
    COMPLEMENTS = 'COMPLEMENTS',
    KEYWORDBROADMATCH = 'KEYWORD_BROAD_MATCH',
    KEYWORDEXACTMATCH = 'KEYWORD_EXACT_MATCH',
    KEYWORDPHRASEMATCH = 'KEYWORD_PHRASE_MATCH'
}

