/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BidValues } from './bid-values';
/**
 * 
 * @export
 * @interface ThemedBid
 */
export interface ThemedBid {
    /**
     * 
     * @type {BidValues}
     * @memberof ThemedBid
     */
    suggestedBid?: BidValues;
    /**
     * Keyword match type. The default value will be BROAD.
     * @type {string}
     * @memberof ThemedBid
     */
    matchType?: ThemedBidMatchTypeEnum;
    /**
     * The keyword target rank.
     * @type {number}
     * @memberof ThemedBid
     */
    rank?: number;
    /**
     * The theme of the bid recommendation. The default theme is CONVERSION_OPPORTUNITIES.
     * @type {string}
     * @memberof ThemedBid
     */
    theme?: string;
    /**
     * The bid value for the keyword. The default value will be the suggested bid.
     * @type {number}
     * @memberof ThemedBid
     */
    bid?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ThemedBidMatchTypeEnum {
    BROAD = 'BROAD',
    EXACT = 'EXACT',
    PHRASE = 'PHRASE'
}

