/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Recommended asins grouped by theme attribute.
 * @export
 * @interface ThemeRecommendation
 */
export interface ThemeRecommendation {
    /**
     * A theme name representing the context around the recommended list of ASINs.
     * @type {string}
     * @memberof ThemeRecommendation
     */
    description?: string;
    /**
     * List of recommended ASINs under current theme.
     * @type {Array<string>}
     * @memberof ThemeRecommendation
     */
    recommendedAsins?: Array<string>;
    /**
     * A theme name representing the context around the recommended list of ASINs.
     * @type {string}
     * @memberof ThemeRecommendation
     */
    theme?: string;
}
