/* tslint:disable */
/* eslint-disable */
/**
 * Sponsored Products
 *  
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Returns information about UnprocessableEntityException.
 * @export
 * @interface UnprocessableEntityException
 */
export interface UnprocessableEntityException {
    /**
     * The HTTP status code of the response.
     * @type {string}
     * @memberof UnprocessableEntityException
     */
    code?: string;
    /**
     * A human-readable description of the response.
     * @type {string}
     * @memberof UnprocessableEntityException
     */
    details?: string;
}
